import {createWorkbench} from './workbench.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {createInCarEngine} from './engine/in-car.js';
import {enhanceCar} from './car-look.js';
import {createSurfaceLibrary} from './surface-library.js';
import {createSennaDriver} from './senna-driver.js';
import {applyInteiaBranding} from './branding.js';
import {brandSVG} from './identity.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createGarage} from './garage.js';
import {createWindTunnel} from './wind-tunnel.js';
import {setupCustomization} from './customize.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {setupStudio,applyCarMaterials} from './studio.js';
import {createMechanics} from './mechanics.js';
const $=s=>document.querySelector(s),stage=$('#stage'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
document.getElementById('brand-logo').innerHTML=brandSVG();
const categoryLabels={body:'Carroceria',aero:'Aerodinâmica',wheels:'Rodas e pneus',suspension:'Suspensão',cockpit:'Cockpit',details:'Detalhes'};
try{
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));stage.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Carro 3D. Arraste para girar. Setas giram a câmera; mais e menos controlam o zoom.');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.04,150),studio=setupStudio(THREE,renderer,scene);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,512,512,16);ao.kernelRadius=.14;ao.minDistance=.0001;ao.maxDistance=.015;composer.addPass(ao);composer.addPass(new OutputPass());composer.addPass(new SMAAPass());let highQuality=true;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=.35;controls.maxDistance=30;controls.maxPolarAngle=Math.PI-.015;controls.autoRotateSpeed=.6;
const gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSize(.7);const gizmoHelper=gizmo.getHelper();scene.add(gizmoHelper);gizmo.enabled=false;let freeMove=false;
gizmo.addEventListener('dragging-changed',e=>{controls.enabled=!e.value;if(mechanics)mechanics.drag(e.value);if(e.value){$('#loop').setAttribute('aria-pressed','false');$('#spin').setAttribute('aria-pressed','false');$('#steering').value=0;$('#drs').value=0;$('#steering-value').textContent=$('#drs-value').textContent='0°';}});
let garage,garageWasActive=false,engine,carLook,driver,workbench,engineOpen=false,enginePaused=false;
function closeEngine(){engineOpen=false;if(engine)engine.update(0,null,true);$("#engine-open").setAttribute("aria-pressed","false");$("#engine-open").textContent="Abrir compartimento do motor";}
let tunnelActive=false,cinematic=false,cinemaTime=0,xraySaved=null;
function setFlowXray(on){
 if(on&&!xraySaved){xraySaved=[];const cache=new Map();model.traverse(mesh=>{if(!mesh.isMesh)return;const original=mesh.material;const floor=/floor|diffus/i.test(mechanics.records[mesh.userData.recordId]?.source||'');const clone=m=>{const key=m.uuid+floor;if(cache.has(key))return cache.get(key);const c=m.clone();c.onBeforeCompile=m.onBeforeCompile;c.customProgramCacheKey=m.customProgramCacheKey;c.opacity=floor?.62:.10;c.transparent=true;c.depthWrite=false;if(floor){c.emissive.set('#22544a');c.emissiveIntensity=.28;}cache.set(key,c);return c;};mesh.material=Array.isArray(original)?original.map(clone):clone(original);xraySaved.push({mesh,original});});
 }else if(!on&&xraySaved){const dispose=new Set();for(const {mesh,original} of xraySaved){for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material])dispose.add(m);mesh.material=original;}dispose.forEach(m=>m.dispose());xraySaved=null;}
}
let windTunnel,model,mechanics,materials,span=5.7,focus=new THREE.Vector3(0,.45,0),distance=10,transition=null,currentView='hero',selectionBox=null,autoFit=true;
const views={hero:[1,.4,1.2],side:[1,.12,0],front:[0,.16,1],rear:[0,.23,-1],top:[.001,1,0],bottom:[.001,-1,0]};
window.viewerInfo={loaded:false};
const loader=$('#loading'),status=$('#status'),assembly=$('#assembly');
function moveCamera(to,target,animate=true){transition=animate&&!reduced.matches?{start:performance.now(),from:camera.position.clone(),to,fromTarget:controls.target.clone(),target:target.clone()}:null;if(!transition){camera.position.copy(to);controls.target.copy(target);controls.update();}}
function view(name,animate=true){if(workbench?.inspecting){workbench.view(name);return;}currentView=name;autoFit=true;const expanded=mechanics?1+mechanics.target*.52:1;const target=focus.clone();target.y+=mechanics?mechanics.target*.45:0;moveCamera(target.clone().addScaledVector(new THREE.Vector3(...views[name]).normalize(),distance*expanded),target,animate);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));}
let priorWidth=0,priorHeight=0;
function resize(){const previousDistance=distance;const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();distance=span*(w<600?.58:.65)/Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/Math.min(camera.aspect,1.5);if(model&&(tunnelActive||garage?.enabled)&&priorWidth&&!cinematic&&!autoFit){camera.position.sub(controls.target).multiplyScalar(distance/previousDistance).add(controls.target);controls.update();}else if(model&&(!priorWidth||autoFit))view(currentView,false);priorWidth=w;priorHeight=h;}
new ResizeObserver(resize).observe(stage);resize();
function refreshSelection(){const r=mechanics.selected===null?null:mechanics.records[mechanics.selected];$('#selected-name').textContent=r?r.label:'Escolha uma peça';$('#selected-category').textContent=r?categoryLabels[r.category]:'Clique no carro ou escolha na lista.';$('#part-offset').disabled=!r;$('#focus-part').disabled=!r;$('#isolate').disabled=!r;$('#isolate').setAttribute('aria-pressed',String(mechanics.isolated));$('#part-offset').value=r?r.manual*100:0;$('#offset-value').textContent=r?Math.round(r.manual*100)+'%':'0%';$('#part-select').value=r?r.id:'';if(selectionBox){scene.remove(selectionBox);selectionBox.dispose();selectionBox=null;}if(r){selectionBox=new THREE.BoxHelper(r.root,0xa92320);selectionBox.material.transparent=true;selectionBox.material.opacity=.4;selectionBox.material.depthTest=false;scene.add(selectionBox);selectionBox.visible=!document.body.classList.contains("photo");}}
function select(id){closeEngine();mechanics.select(id===null?null:Number(id));refreshSelection();const r=mechanics.selected===null?null:mechanics.records[mechanics.selected];$('#free-move').disabled=!r;gizmo.detach();if(r&&freeMove)gizmo.attach(r.root);gizmo.enabled=!!r&&freeMove;}
function focusPart(){if(mechanics.selected===null)return;const r=mechanics.records[mechanics.selected],box=new THREE.Box3().setFromObject(r.root),size=box.getSize(new THREE.Vector3()),target=box.getCenter(new THREE.Vector3());const d=Math.max(size.length()*1.45,.65)/Math.min(camera.aspect,1);autoFit=false;moveCamera(target.clone().addScaledVector(camera.position.clone().sub(controls.target).normalize(),d),target);}
function assemblyTo(v){if(engineOpen){autoFit=true;currentView="hero";}closeEngine();engine?.prepare();mechanics.setAmount(v);assembly.value=Math.round(v*100);$('#assembly-value').textContent=Math.round(v*100)+'%';$('#loop').setAttribute('aria-pressed','false');if(autoFit)view(currentView);}
const raw=Uint8Array.from(atob($('#model-data').textContent.trim()),c=>c.charCodeAt(0));
new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parse(raw.buffer,'',async g=>{
 try{
 model=g.scene;const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);scene.add(model);span=Math.max(size.x,size.z);focus.set(0,size.y*.43,0);model.updateMatrixWorld(true);
 materials=applyCarMaterials(THREE,model);mechanics=createMechanics(model);await applyInteiaBranding(model,mechanics);
 const surfaces=createSurfaceLibrary(THREE,{renderer,mobile:innerWidth<700});
 for(const m of materials.materials){const n=m.name.toLowerCase();const kind=n.startsWith('pintura')?'paint':n.includes('carbon')?'carbon':['pneus','borracha'].includes(n)?'rubber':n==='aço'?'aluminum':null;if(kind)surfaces.applyTo(m,kind,{uvSpanMeters:n==='pneus'?.65:1});}
 carLook=enhanceCar({model,mechanics,mobile:innerWidth<700});driver=createSennaDriver(model,mechanics);
 setupCustomization(materials,studio,renderer,scene);
 for(const [id,name] of [['body','pintura'],['wings','pintura'],['wheels','rodas'],['carbon','carbon']]){const m=materials.materials.find(m=>m.name.toLowerCase().includes(name));if(m){$('#color-'+id).value='#'+m.color.getHexString();$('#value-'+id).textContent=('#'+m.color.getHexString()).toUpperCase();}}
 engine=createInCarEngine({scene,renderer,camera,model,mechanics,target:()=>composer.readBuffer,mobile:innerWidth<700});
 garage=createGarage({scene,renderer,studio,camera,mechanics});garage.setEnabled(true);windTunnel=createWindTunnel({scene,model,mechanics,reduced,studio,camera,onBeforeToggle:on=>{closeEngine();if(on){garageWasActive=garage.enabled;garage.setEnabled(false);}},onRegion:region=>{setFlowXray(region==='floor');cinematic=false;$('#wind-cinema').setAttribute('aria-pressed','false');controls.autoRotate=false;$('#orbit').setAttribute('aria-pressed','false');autoFit=false;const target=focus.clone();let direction=new THREE.Vector3(1,.28,1.4),scale=1.14;if(region==='wheels'){target.z=-span*.43;direction.set(1,.38,-.85);scale=1.10;}if(region==='floor'){target.y=.20;direction.set(1,.8,.5);scale=1.05;}moveCamera(target.clone().addScaledVector(direction.normalize(),distance*scale),target);},onToggle:on=>{if(!on&&garageWasActive)garage.setEnabled(true);setFlowXray(on&&$('#flow-region').value==='floor'&&$('#flow-detail').getAttribute('aria-pressed')==='true');tunnelActive=on;cinematic=false;$("#wind-cinema").setAttribute("aria-pressed","false");controls.autoRotate=false;$("#orbit").setAttribute("aria-pressed","false");autoFit=false;const target=focus.clone();target.y+=on?.15:0;moveCamera(target.clone().addScaledVector(new THREE.Vector3(1,.28,1.4).normalize(),distance*(on?1.14:1)),target);}});
 workbench=createWorkbench({scene,model,driver,engine,garage,controls,camera,moveCamera,closeEngine,showCar:()=>view('hero')});
 const options=$('#part-select');for(const [category,label] of Object.entries(categoryLabels)){const group=document.createElement('optgroup');group.label=label;mechanics.records.filter(r=>r.category===category).forEach(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.label;group.append(o);});options.append(group);}
 $('#part-count').textContent=mechanics.records.length;loader.hidden=true;status.textContent='ESTÚDIO PRONTO';document.body.classList.add('ready');document.querySelectorAll('[data-needs-model]').forEach(e=>e.disabled=false);resize();
 window.viewerInfo={loaded:true,parts:mechanics.records.length,triangles:0,source:'INTEIA F1 Loop · carro final v2',sponsors:'INTEIA / Inteligência Mil Grau',version:'2026-09-15-piloto-lab' };model.traverse(o=>{if(o.isMesh)window.viewerInfo.triangles+=(o.geometry.index?o.geometry.index.count:o.geometry.attributes.position.count)/3;});
}catch(e){console.error(e);loader.textContent='Falha ao preparar o carro ou os patrocínios. Recarregue a página.';status.textContent='FALHA NO CARREGAMENTO';}
},e=>{console.error(e);loader.textContent='Não foi possível abrir o modelo. Recarregue a página.';status.textContent='FALHA NO CARREGAMENTO';});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{cinematic=false;$('#wind-cinema').setAttribute('aria-pressed','false');controls.autoRotate=false;$('#orbit').setAttribute('aria-pressed','false');view(b.dataset.view);});
$('#garage-toggle').onclick=()=>{if(tunnelActive){$('#wind-toggle').click();garage.setEnabled(true);}else garage.setEnabled(!garage.enabled);view('hero');};
$('#garage-export').onclick=async()=>{const button=$('#garage-export');button.disabled=true;button.textContent='Preparando GLB…';try{const data=await new GLTFExporter().parseAsync(garage.getExportScene(),{binary:true,onlyVisible:false});const url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download='INTEIA-box-laboratorio.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){console.error(e);status.textContent='Não foi possível exportar o box.';}finally{button.disabled=false;button.textContent='Baixar box 3D';}};
$('#garage-view').onclick=()=>{autoFit=false;const target=new THREE.Vector3(0,1,-1.2);moveCamera(target.clone().addScaledVector(new THREE.Vector3(.65,.40,1).normalize(),distance*1.4),target);};
$('#orbit').onclick=()=>{cinematic=false;$('#wind-cinema').setAttribute('aria-pressed','false');controls.autoRotate=!controls.autoRotate;$('#orbit').setAttribute('aria-pressed',String(controls.autoRotate));};
$('#theme').onclick=()=>{const dark=document.body.classList.toggle('dark');studio.setTheme(dark);$('#theme').setAttribute('aria-pressed',String(dark));$('#theme').textContent=dark?'Estúdio claro':'Estúdio escuro';};
$('#quality').onclick=()=>{highQuality=!highQuality;$('#quality').setAttribute('aria-pressed',String(highQuality));$('#quality').textContent=highQuality?'Qualidade alta · oclusão e antialiasing':'Modo leve · sem pós-processamento';};
$('#wire').onclick=()=>{const enabled=$('#wire').getAttribute('aria-pressed')!=='true';materials.materials.forEach(m=>m.wireframe=enabled);$('#wire').setAttribute('aria-pressed',String(enabled));};
assembly.oninput=()=>assemblyTo(Number(assembly.value)/100);
$('#explode').onclick=()=>assemblyTo(1);$('#assemble').onclick=()=>{mechanics.restoreParts();assemblyTo(0);refreshSelection();};
$('#loop').onclick=()=>{closeEngine();engine?.prepare();mechanics.toggleLoop();$('#loop').setAttribute('aria-pressed',String(mechanics.playing));autoFit=true;};
$('#part-select').onchange=e=>select(e.target.value===''?null:e.target.value);
$('#clear-selection').onclick=()=>select(null);$('#focus-part').onclick=focusPart;$('#isolate').onclick=()=>{mechanics.isolate();refreshSelection();};
$('#free-move').onclick=()=>{freeMove=!freeMove;$('#free-move').setAttribute('aria-pressed',String(freeMove));gizmo.enabled=freeMove;if(freeMove&&mechanics.selected!==null)gizmo.attach(mechanics.records[mechanics.selected].root);else gizmo.detach();};
$('#part-offset').oninput=e=>{mechanics.setManual(Number(e.target.value)/100);$('#offset-value').textContent=e.target.value+'%';};
$('#spin').onclick=()=>{const on=$('#spin').getAttribute('aria-pressed')!=='true';mechanics.setSpin(on);$('#spin').setAttribute('aria-pressed',String(on));};
$('#steering').oninput=e=>{mechanics.setSteering(Number(e.target.value));$('#steering-value').textContent=e.target.value+'°';};
$('#drs').oninput=e=>{mechanics.setDRS(Number(e.target.value));$('#drs-value').textContent=e.target.value+'°';};
$('#reset').onclick=()=>{closeEngine();mechanics.reset();freeMove=false;gizmo.detach();gizmo.enabled=false;$('#free-move').setAttribute('aria-pressed','false');select(null);controls.autoRotate=false;['orbit','loop','spin'].forEach(id=>$('#'+id).setAttribute('aria-pressed','false'));['assembly','steering','drs'].forEach(id=>$('#'+id).value=0);$('#assembly-value').textContent='0%';$('#steering-value').textContent=$('#drs-value').textContent='0°';view('hero');workbench?.reset();};
$('#zoom-in').onclick=()=>{autoFit=false;camera.position.lerp(controls.target,.15);controls.update();};$('#zoom-out').onclick=()=>{autoFit=false;camera.position.sub(controls.target).multiplyScalar(1.18).add(controls.target);controls.update();};
$('#photo').onclick=()=>{document.body.classList.toggle('photo');$('#photo').setAttribute('aria-pressed',String(document.body.classList.contains('photo')));if(selectionBox)selectionBox.visible=!document.body.classList.contains('photo');gizmoHelper.visible=!document.body.classList.contains('photo');};
$('#save-photo').onclick=()=>{const boxVisible=selectionBox?.visible,gizmoVisible=gizmoHelper.visible;if(selectionBox)selectionBox.visible=false;gizmoHelper.visible=false;highQuality?composer.render():renderer.render(scene,camera);const a=document.createElement('a');a.download='INTEIA-design-3D.png';a.href=renderer.domElement.toDataURL('image/png');a.click();if(selectionBox)selectionBox.visible=boxVisible;gizmoHelper.visible=gizmoVisible;};
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);
renderer.domElement.addEventListener('pointerup',e=>{if(workbench?.inspecting||!model||gizmo.axis||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObject(model,true).filter(h=>{let o=h.object;while(o&&o!==model){if(!o.visible)return false;o=o.parent;}return true;});if(hits.length&&hits[0].object.userData.recordId!==undefined)select(hits[0].object.userData.recordId);});
renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home')view('hero');if(e.key==='Escape'&&mechanics)select(null);if(e.key==='+'||e.key==='=')$('#zoom-in').click();if(e.key==='-')$('#zoom-out').click();if(e.key.startsWith('Arrow')){autoFit=false;const offset=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')offset.applyAxisAngle(new THREE.Vector3(0,1,0),e.key==='ArrowLeft'?.1:-.1);else{const spherical=new THREE.Spherical().setFromVector3(offset);spherical.phi=THREE.MathUtils.clamp(spherical.phi+(e.key==='ArrowUp'?-.1:.1),.02,controls.maxPolarAngle);offset.setFromSpherical(spherical);}camera.position.copy(controls.target).add(offset);e.preventDefault();}});
$('#engine-open').onclick=()=>{if(engineOpen){closeEngine();view('hero');return;}if(tunnelActive)$('#wind-toggle').click();$('#reset').click();engineOpen=true;engine.prepare();$('#engine-open').setAttribute('aria-pressed','true');$('#engine-open').textContent='Fechar compartimento do motor';autoFit=false;moveCamera(new THREE.Vector3(1.8,1.65,-2.35),new THREE.Vector3(0,.52,-.75));};
$('#engine-pause').onclick=()=>{enginePaused=!enginePaused;$('#engine-pause').setAttribute('aria-pressed',String(enginePaused));$('#engine-pause').textContent=enginePaused?'Retomar motor':'Pausar motor';};
$('#engine-cut').oninput=()=>{$('#engine-cut-value').textContent=$('#engine-cut').value+'%';};
$('#wind-cinema').onclick=()=>{cinematic=!cinematic;$('#wind-cinema').setAttribute('aria-pressed',String(cinematic));controls.autoRotate=false;$('#orbit').setAttribute('aria-pressed','false');transition=null;cinemaTime=0;};
controls.addEventListener('start',()=>{cinematic=false;$('#wind-cinema').setAttribute('aria-pressed','false');transition=null;autoFit=false;});
let last=performance.now(),lastTarget=0,frameCount=0,frameStart=performance.now();
renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.05);last=now;if(mechanics){mechanics.update(dt,now,reduced.matches);if(mechanics.playing){assembly.value=Math.round(mechanics.amount*100);$('#assembly-value').textContent=Math.round(mechanics.amount*100)+'%';if(lastTarget!==mechanics.target){view(currentView);lastTarget=mechanics.target;}}const paused=!mechanics.motionAvailable;$('#motion-note').hidden=!paused;['spin','steering','drs'].forEach(id=>$('#'+id).disabled=paused);$('#assembly-state').textContent=mechanics.amount<.001?'MONTADO':mechanics.amount>.999?'DESMONTADO':'EM TRANSIÇÃO';carLook?.update();driver?.update();if(driver)driver.root.visible=mechanics.motionAvailable&&!mechanics.isolated;engine?.update(dt,engineOpen?{open:1,cut:Number($('#engine-cut').value)/100,light:1}:null,enginePaused);if(engine){$('#engine-status').textContent=engine.state==='loading'?'Carregando motor…':engine.state==='failed'?'Motor indisponível. Recarregue para tentar novamente.':engine.ready?'Motor pronto · V6 ilustrativo':'Motor disponível sob demanda';$('#engine-cut').disabled=!engine.ready||!engineOpen;$('#engine-pause').disabled=!engine.ready;window.viewerInfo.engineState=engine.state;window.viewerInfo.engineOpen=engineOpen;window.viewerInfo.engineVisible=engine.root.visible;}workbench?.update();if(selectionBox)selectionBox.update();window.viewerInfo.assembly=mechanics.amount;window.viewerInfo.motionAvailable=mechanics.motionAvailable;}
 if(transition){const t=Math.min(1,(now-transition.start)/800),s=1-(1-t)**3;camera.position.lerpVectors(transition.from,transition.to,s);controls.target.lerpVectors(transition.fromTarget,transition.target,s);if(t===1)transition=null;}if(tunnelActive&&cinematic&&!reduced.matches){cinemaTime+=dt;const angle=.66+Math.sin(cinemaTime*.14)*.18;const radius=distance*1.14;const target=focus.clone();target.y+=.3;camera.position.set(Math.sin(angle)*radius,target.y+radius*(.32+.025*Math.sin(cinemaTime*.11)),Math.cos(angle)*radius);controls.target.copy(target);}controls.update(dt);studio.update(dt);garage?.update(dt);windTunnel?.update(dt);studio.floor.visible=camera.position.y>0;highQuality?composer.render():renderer.render(scene,camera);frameCount++;if(now-frameStart>2000){document.body.dataset.fps=String(Math.round(frameCount*1000/(now-frameStart)));frameCount=0;frameStart=now;}if(mechanics){document.body.dataset.parts=mechanics.records.length;document.body.dataset.assembly=mechanics.amount.toFixed(4);}});
}catch(e){console.error(e);$('#loading').textContent='O 3D não pôde iniciar. Abra no Chrome ou Edge com aceleração gráfica.';}
