// Base didática das peças dos sistemas internos: para cada família de peça (por padrão no nome),
// o que ela faz, para que serve e uma curiosidade técnica. Consultada ao clicar em uma peça na bancada
// Sistemas. Conteúdo original INTEIA, escrito para estudo; valores são ordens de grandeza típicas
// da categoria, não dados homologados de nenhuma equipe.

const R = (pattern, funcao, curiosidade) => ({pattern, funcao, curiosidade});

const RULES = [
 // ---------------------------------------------------------------- segurança
 R(/^Halo/, 'Arco de titânio que protege a cabeça do piloto contra rodas soltas, destroços e impactos com barreiras. Fixa-se em três pontos do chassi: dois atrás do cockpit e um no pilar central.',
  'Pesa cerca de 7 kg e suporta 125 kN, o peso de um ônibus de dois andares apoiado sobre ele. Salvou Grosjean em 2020 e Zhou em 2022.'),
 R(/^Fixação (traseira|dianteira) do Halo|^Parafusos da fixação/, 'Pontos de ancoragem do Halo ao chassi. As fixações traseiras recebem a maior parte da carga em impacto lateral; a dianteira estabiliza o pilar.',
  'Cada fixação passa por ensaio estático com carga aplicada em direções diferentes: para cima, para trás e lateralmente, sem que o arco ceda mais que alguns milímetros.'),
 R(/^Estrutura principal de capotamento|^Escora da estrutura|^Base da estrutura de capotamento/, 'Arco de segurança escondido dentro do airbox: é o ponto mais alto do carro e sustenta o peso do carro capotado, mantendo espaço acima do capacete.',
  'Após acidentes recentes, o teste passou a exigir carga combinada de mais de 100 kN; o arco é feito em titânio ou compósito metálico junto com a entrada de ar do motor.'),
 R(/^Cone de impacto dianteiro|^Antepara de colapso z/, 'Estrutura de nariz projetada para se esmagar progressivamente, transformando a energia do impacto frontal em deformação controlada do laminado.',
  'Deve absorver o choque a 15 m/s com desaceleração média abaixo de 40 g; o laminado é feito para se desfazer em fragmentos, e não para dobrar.'),
 R(/^Estrutura de impacto traseira|^Antepara de colapso traseira/, 'Cone atrás do câmbio que absorve impactos traseiros e serve de base para a asa traseira e a luz de chuva.',
  'É parafusada à carcaça do câmbio e ensaiada à parte: a carcaça precisa sobreviver ao teste sem trincas para a estrutura ser homologada.'),
 R(/^Tubo anti-intrusão|^Flange do tubo anti-intrusão/, 'Tubos cônicos de carbono no costado do chassi que impedem que uma ponta de asa ou destroço penetre o cockpit em colisão lateral.',
  'Há dois por lado, escondidos dentro do sidepod. O regulamento define até o cone de ataque que o tubo tem de resistir em um teste de perfuração.'),
 R(/^Cabo de retenção|^Terminal do cabo de retenção/, 'Cabos de Zylon que ligam cada roda ao chassi pelos braços da suspensão, para a roda não sair voando após um acidente.',
  'São três por roda desde 2018, cada um suportando 70 kN. O Zylon é a mesma fibra dos coletes balísticos e do painel anti-intrusão do cockpit.'),
 R(/^Encosto de cabeça|^Pino de retenção do encosto/, 'Acolchoado em U que envolve a cabeça do piloto, absorvendo o impacto do capacete nos choques laterais e traseiros.',
  'A espuma tem densidade escolhida conforme a temperatura do dia, porque endurece no frio. Ele é removível para o resgate e possui uma alça de puxar.'),
 R(/^Extintor|^Válvula do extintor|^Bico do extintor/, 'Sistema de extinção obrigatório: uma garrafa com agente extintor e bicos direcionados para o cockpit e para o compartimento do motor.',
  'Pode ser acionado pelo piloto, pelos comissários por uma chave externa ou automaticamente por sensor térmico; descarrega durante alguns segundos.'),
 R(/^Chave externa|^Marcação de corte geral/, 'Chaves acessíveis pelos comissários fora do carro: cortam a energia elétrica e disparam o extintor sem que ninguém precise entrar no cockpit.',
  'A chave é marcada com o raio vermelho em triângulo azul (letra E), padrão obrigatório para que qualquer socorrista a identifique em segundos.'),
 R(/^Luz de chuva/, 'Luz vermelha traseira obrigatória, acesa em chuva ou baixa visibilidade e piscando quando o carro recupera energia com o ERS.',
  'Pisca também quando o motor não está entregando potência em modo de carga, avisando o carro de trás que a velocidade pode cair de repente.'),

 // ---------------------------------------------------------------- volante
 R(/^Corpo do volante|^Tampa traseira de carbono/, 'Corpo estrutural em fibra de carbono que abriga a eletrônica e sustenta todos os comandos; é o principal painel de controle do piloto.',
  'Um volante completo custa em torno de 50 mil euros e pesa cerca de 1,3 kg. O piloto o retira em segundos pelo engate rápido para sair do cockpit.'),
 R(/^Placa eletrônica do volante/, 'Placa que lê botões, seletores e borboletas e conversa com a unidade de controle do carro por um único conector, além de alimentar o display.',
  'Toda a informação trafega por barramento CAN; o volante é apenas uma interface, e o motor pode ser controlado sem ele durante testes na garagem.'),
 R(/^Empunhadura/, 'Empunhaduras moldadas em borracha sobre as quais o piloto mantém as mãos sempre na mesma posição, sem cruzar os braços.',
  'São moldadas à mão do piloto e ficam na vertical porque o volante gira pouco: menos de meia volta de batente a batente.'),
 R(/^Rolo de polegar/, 'Roda dentada operada pelo polegar para ajustes finos durante a curva, como diferencial de entrada ou recuperação de energia.',
  'Ferramenta favorita para mudar o balanço do carro sem tirar a mão da empunhadura; alguns pilotos a acionam várias vezes por volta.'),
 R(/^Moldura do display|^Display LCD central/, 'Tela colorida onde o piloto lê marcha, tempos, delta para o rival, temperaturas e alertas; as páginas mudam conforme o botão pressionado.',
  'O display padronizado, fornecido pela McLaren Applied, exibe até 100 páginas configuráveis. A marcha aparece grande porque é lida de relance na frenagem.'),
 R(/^LED de troca/, 'Régua de quinze LEDs que acende progressivamente com a rotação do motor: verdes, vermelhos e azuis indicam o momento exato de subir a marcha.',
  'Os pilotos trocam pelos LEDs e pelo som; um atraso de 200 ms na troca custa alguns centésimos por volta.'),
 R(/^LED de bandeira/, 'LEDs laterais que replicam as bandeiras da direção de prova: amarela, azul, branca, vermelha, além de avisos do carro de segurança virtual.',
  'Desde 2021 os painéis eletrônicos da pista falam com o carro por rádio, e a bandeira acende no volante mesmo antes de o piloto ver o painel.'),
 R(/^Botão · N /, 'Coloca o câmbio em ponto morto, necessário para parar nos boxes, sair de uma escapada ou permitir que os comissários empurrem o carro.',
  'Como o piloto não consegue selecionar neutro acidentalmente, o botão fica em posição protegida e costuma exigir um toque longo.'),
 R(/^Botão · R /, 'Abre o canal de rádio com o engenheiro de pista.', 'O rádio só transmite enquanto o botão está pressionado, por isso as mensagens dos pilotos costumam ser curtas e cortadas.'),
 R(/^Botão · DRINK/, 'Aciona a bomba de hidratação que envia bebida do saco no cockpit ao tubo do capacete.',
  'O piloto perde até 3 kg de líquido em uma corrida quente; a bebida esquenta tanto que muitos preferem não usá-la depois de metade da prova.'),
 R(/^Botão · OT /, 'Override manual: no regulamento 2026, libera potência elétrica extra quando o piloto está a menos de um segundo do carro da frente, substituindo o DRS como ferramenta de ultrapassagem.',
  'A regra de 2026 permite entregar até 350 kW do MGU-K acima de 290 km/h ao perseguidor, enquanto o carro da frente tem a potência elétrica reduzida.'),
 R(/^Botão · OK /, 'Confirma a seleção feita nos seletores rotativos ou fecha um alerta no display.', 'Muitas mudanças de mapa só entram em vigor após o OK, para evitar que um esbarrão no seletor mude o comportamento do motor.'),
 R(/^Botão · P /, 'Limitador de velocidade dos boxes: trava o carro na velocidade máxima permitida na área de box, geralmente 80 km/h.',
  'Ao ser acionado ele também prepara o carro para a parada, ajustando embreagem e mapas. Esquecer de ativá-lo custa multa e às vezes penalidade na pista.'),
 R(/^Botão · K1/, 'Libera um modo de recuperação ou entrega extra de energia por alguns segundos, usado em largadas, relargadas e defesas.',
  'A energia extra sai da bateria e precisa ser recuperada nas frenagens seguintes; os engenheiros avisam pelo rádio quanto ainda há para gastar.'),
 R(/^Botão · AA /, 'Aerodinâmica ativa de 2026: alterna entre o modo X, de baixa resistência para as retas, e o modo Z, de alta carga para as curvas, movendo asas dianteira e traseira.',
  'Diferente do DRS, a mudança para o modo X é permitida a todos os carros em zonas definidas, e não só a quem está perseguindo.'),
 R(/^Botão · SOC/, 'Seleciona a estratégia de carga da bateria: manter, carregar mais nas frenagens ou gastar tudo até o fim da volta.',
  'Com a bateria de 2026 tendo de fornecer quase metade da potência total, a gestão de carga tornou-se tão decisiva quanto a escolha de pneus.'),
 R(/^Botão · KO/, 'Cancela a última seleção ou apaga um alerta sem executar nada.', 'Existe para desfazer toques errados, comuns com luvas e sob 5 g de força lateral.'),
 R(/^Botão · PF/, 'Confirma ao muro que o piloto vai entrar nos boxes na volta corrente, disparando a preparação da equipe.',
  'A confirmação também ativa a contagem no cronômetro dos mecânicos; paradas hoje duram menos de 2,5 s.'),
 R(/^Botão · FLAG/, 'Confirma que o piloto viu uma bandeira ou mensagem enviada pela direção de prova.',
  'Sem a confirmação, alguns avisos continuam piscando no display até a mensagem ser reconhecida.'),
 R(/^Legenda /, 'Gravação a laser que identifica o botão; a cor e a posição são padronizadas para o piloto encontrar o comando sem olhar.',
  'Cada piloto define seu próprio leiaute, e o mesmo modelo de volante muda de time a time apenas na disposição das legendas.'),
 R(/^Balancim BMIG/, 'Ajusta a migração de freio: quanto do balanço de frenagem se move para a traseira conforme o pedal é solto no meio da curva.',
  'A migração compensa a mudança de carga entre os eixos quando o piloto vai aliviando o freio; é reajustada quase toda volta conforme o pneu se desgasta.'),
 R(/^Balancim BBAL/, 'Ajusta o balanço de freio entre dianteira e traseira em passos de 1%, deslocando o ponto de apoio da barra de balanço nos cilindros mestres.',
  'O ajuste é mecânico e chega ao pedal por um cabo ou motor elétrico; o piloto o muda para cada curva em circuitos como Mônaco.'),
 R(/^Seletor MID/, 'Seletor de mapa intermediário para funções auxiliares, como o comportamento do diferencial no meio da curva.',
  'O diferencial de deslizamento controlado hidraulicamente pode ser ajustado separadamente para entrada, meio e saída de curva.'),
 R(/^Seletor EB/, 'Ajusta o freio-motor: a resistência do motor de combustão quando o piloto solta o acelerador, que afeta a estabilidade na frenagem.',
  'Com o MGU-K recuperando energia, o freio-motor real é pequeno; o mapa serve para o carro ficar previsível ao aliviar o pedal.'),
 R(/^Seletor multifunção esquerdo/, 'Seletor de estratégia: escolhe planos pré-programados de energia e combustível para a volta, como economia, ataque ou qualificação.',
  'Cada posição muda dezenas de parâmetros de uma vez; o engenheiro pede pelo rádio "estratégia 4" e o piloto gira até o número.'),
 R(/^Seletor central/, 'Seletor principal de modo: corrida, boxes, largada, teste ou volta de aquecimento, o mais usado durante a prova.',
  'A posição de largada ajusta a embreagem e a entrega de torque para as primeiras marchas; errar o modo na largada custa posições.'),
 R(/^Seletor multifunção direito/, 'Seletor de energia: define quanto o sistema híbrido entrega e recupera em cada trecho da volta.',
  'Doze posições cobrem de "recarregar tudo" até "descarga total", com mapas intermediários pensados para cada circuito.'),
 R(/^Tampa usinada|^Indicador ·|^Posição \d+ ·/, 'Detalhe do seletor rotativo: tampa usinada em alumínio, indicador de posição e marcas coloridas que o piloto identifica de relance.',
  'As cores seguem um código pessoal do piloto e são gravadas na fábrica; as marcas ajudam a checar a posição pelo reflexo na viseira.'),
 R(/^Emblema INTEIA|^Gravação INTEIA/, 'Identidade visual do laboratório gravada na peça.', 'Nos volantes reais esse espaço recebe o logotipo do fabricante do volante ou o número do piloto.'),
 R(/^Borboleta de marcha/, 'Alavancas atrás do volante para trocar de marcha: a direita sobe e a esquerda desce; o câmbio sequencial executa a troca em milésimos.',
  'A troca leva menos de 50 ms e não corta o acelerador; alguns pilotos preferem borboletas ligadas entre si para trocar com qualquer mão.'),
 R(/^Borboleta de embreagem/, 'Alavancas de embreagem operadas pelos dedos, usadas na largada e nas paradas; não há pedal de embreagem no cockpit.',
  'O ponto de mordida é encontrado com precisão de milímetros na volta de apresentação; por regra, o mapeamento tem de ser linear.'),
 R(/^Sensor da borboleta/, 'Sensor de posição que lê o curso de cada borboleta e informa a unidade de controle quando comandar a troca ou a embreagem.',
  'É redundante: dois sensores leem o mesmo curso e a eletrônica compara os valores antes de aceitar o comando.'),
 R(/^Engate rápido/, 'Cubo de liberação rápida que prende o volante à coluna; puxar o anel solta o volante para o piloto sair do carro.',
  'O regulamento exige que o piloto consiga sair do cockpit em 5 segundos e recolocar o volante em mais 5.'),
 R(/^Eixo estriado/, 'Eixo estriado que transmite o giro do volante à coluna de direção, garantindo o alinhamento sempre na mesma posição.',
  'A estria é assimétrica para o volante encaixar em uma única orientação, sem risco de montá-lo torto após uma parada.'),
 R(/^Conector elétrico do volante|^Cabo helicoidal/, 'Conexão elétrica de energia e dados entre o volante e o carro, com cabo em espiral para acompanhar o giro da direção.',
  'O conector se separa junto com o engate rápido; um pino de terra mais longo garante que a alimentação só seja ligada depois do aterramento.'),

 // ---------------------------------------------------------------- cockpit
 R(/^Assento moldado/, 'Assento em fibra de carbono moldado sobre o corpo do piloto, que o mantém firme e serve de maca rígida em caso de resgate.',
  'É feito sentando o piloto em um saco de espuma expansível; o molde vira o assento definitivo. Em resgate, o piloto sai do carro junto com o assento.'),
 R(/^Apoio lateral de coxa|^Acolchoado de perna/, 'Acolchoados que travam as pernas e o quadril nas curvas de alta carga lateral e protegem os joelhos contra o chassi.',
  'Com 5 g laterais, a perna do piloto pesa o equivalente a 50 kg contra a parede do cockpit; sem os apoios ele não conseguiria dosar o pedal.'),
 R(/^Cadarço de ombro|^Cadarço de cintura|^Cadarço de virilha/, 'Cadarços do arnês de seis pontos: dois nos ombros, dois na cintura e dois na virilha, todos convergindo para um único fecho.',
  'Os cadarços são apertados a ponto de o piloto não conseguir respirar fundo; ele reaperta na volta de apresentação porque o corpo se acomoda.'),
 R(/^Ajustador do cadarço|^Ancoragem de ombro|^Ancoragem de cintura/, 'Ferragens de ajuste e ancoragem do arnês, fixadas diretamente no chassi de carbono.',
  'As ancoragens são ensaiadas com carga equivalente a dezenas de vezes o peso do piloto; os cadarços têm validade e são trocados a cada temporada.'),
 R(/^Fecho rotativo|^Alavanca de liberação do fecho/, 'Fecho central que solta todos os seis cadarços com um único giro da alavanca, para saída rápida ou resgate.',
  'Após um acidente, o piloto abre o fecho e sai em poucos segundos; o mesmo fecho é usado em aviões de caça.'),
 R(/^HANS/, 'Dispositivo que apoia nos ombros e prende o capacete por dois tirantes, evitando que a cabeça seja lançada para a frente em impacto frontal.',
  'Reduz em mais de 80% a força no pescoço e praticamente eliminou as fraturas da base do crânio que mataram pilotos até os anos 1990.'),
 R(/^Tirante do HANS|^Ancoragem do tirante/, 'Tirantes que ligam o HANS às ancoragens do capacete, permitindo mover a cabeça normalmente mas travando-a em um choque.',
  'O comprimento é ajustado para cada piloto: curto demais limita a visão nas curvas, longo demais atrasa a atuação no impacto.'),
 R(/^Braço do pedal do acelerador|^Pedal do acelerador|^Pivô do pedal do acelerador|^Batente do calcanhar/, 'Pedal do acelerador, operado com o pé direito; move um sensor eletrônico e não um cabo, pois a borboleta é comandada por fio.',
  'O curso e a resistência da mola são ajustados ao gosto do piloto; alguns pedem um batente para não precisar segurar o pé na aceleração plena.'),
 R(/^Sensor de posição do acelerador|^Mola de retorno do acelerador/, 'Sensor duplo que lê a posição do pedal e mola que o devolve ao repouso; a eletrônica compara os dois sinais por segurança.',
  'Se os sensores discordarem, o motor entra em modo de segurança com potência reduzida; o piloto sente como falta de resposta.'),
 R(/^Bolsa de hidratação|^Bomba de hidratação|^Tubo de hidratação/, 'Sistema de bebida: bolsa de 1,5 litro presa ao cockpit, bomba elétrica e tubo até a boca do piloto dentro do capacete.',
  'O líquido é isotônico e às vezes gelado antes da largada; fica quente em poucas voltas por causa do calor do chassi.'),
 R(/^Painel de chaves|^Chave auxiliar/, 'Painel com chaves de funções que o piloto não usa em movimento: ignição, bomba de combustível, rádio e reinício da eletrônica.',
  'Fica escondido atrás do volante ou no costado; o procedimento de partida segue uma lista fixa que o piloto decora.'),
 R(/^Rádio · caixa|^Cabo do rádio/, 'Rádio de comunicação com os boxes, com o transmissor no cockpit e o cabo até os fones do capacete.',
  'As transmissões são criptografadas e também gravadas pela FIA, que as libera para a transmissão de TV com atraso.'),

 // ---------------------------------------------------------------- aerodinâmica
 R(/^Teto do túnel Venturi|^Túnel Venturi|^Assoalho/, 'Canal sob o assoalho que acelera o ar e cria baixa pressão, gerando a maior parte da carga aerodinâmica do carro pelo efeito solo.',
  'Cerca de metade do downforce vem do assoalho; um carro moderno geraria carga suficiente para andar de cabeça para baixo acima de 200 km/h.'),
 R(/^Cerca|^Fence/, 'Cercas na entrada do túnel que organizam vórtices e vedam o assoalho contra o ar que entra pela lateral.',
  'Os vórtices funcionam como paredes invisíveis; quando se rompem em curva lenta o carro perde carga de repente, o famoso "salto".'),
 R(/^Difusor|^Strake/, 'Rampa traseira que devolve o ar de baixa pressão à pressão ambiente, sugando o assoalho para o chão; as lâminas evitam o descolamento.',
  'Quanto mais alto o difusor pode expandir sem descolar o fluxo, mais carga o assoalho gera; o limite é definido pela regra e pela altura de rodagem.'),
 R(/^Asa de viga|^Beam wing/, 'Pequena asa acima da estrutura traseira que ajuda a extrair o ar do difusor e liga o pacote da asa traseira ao assoalho.',
  'Voltou em 2022 justamente para "puxar" o fluxo do difusor; sem ela, o assoalho gerador de efeito solo perderia parte da eficiência.'),
 R(/^Atuador do DRS|^Linha hidráulica do DRS|^Haste de comando do flap|^Pivô do flap DRS|^Braço do DRS/, 'Mecanismo hidráulico que abre o flap da asa traseira em reta para reduzir o arrasto e ganhar velocidade.',
  'Abrir o DRS vale de 10 a 15 km/h no fim da reta. Em 2026 ele dá lugar à aerodinâmica ativa que move as duas asas.'),
 R(/^Bargeboard|^Defletor|^Ajustador de incidência do flap|^Cabeça do ajustador/, 'Elementos que ajustam ou orientam o fluxo em torno do carro; os ajustadores mudam o ângulo do flap dianteiro para equilibrar o carro.',
  'O ajuste do flap dianteiro é feito em segundos nos boxes com uma chave, e é um dos poucos itens mudados durante a corrida.'),
 R(/^Vórtice Y250|^Fluxo externo|^Fluxo /, 'Fita ilustrativa do caminho que o ar percorre; o vórtice Y250 nasce a 250 mm do centro da asa dianteira e organiza o fluxo ao longo do carro.',
  'As equipes usam tinta fluorescente e grades de sensores para ver esses fluxos na pista; aqui eles são representados por fitas animadas.'),

 // ---------------------------------------------------------------- estrutura
 R(/^Célula de sobrevivência|^Chassi|^Monocoque|^Costado|^Casca da célula/, 'Célula de sobrevivência em fibra de carbono e colmeia de alumínio: a estrutura central que protege o piloto e à qual tudo se aparafusa.',
  'Pesa cerca de 35 kg e é feita de mais de mil peças de tecido de carbono curadas em autoclave; passa por 15 ensaios estáticos e dinâmicos.'),
 R(/^Antepara|^Bulkhead/, 'Anteparas internas que dão rigidez à célula e recebem as cargas da suspensão, do motor e do arnês.',
  'A antepara dianteira é a mais espessa: além da suspensão, ela recebe o nariz e é onde os pinos de retenção do cone de impacto se encaixam.'),
 R(/^Prisioneiro|^Escora do motor|^Fixação do motor|^Ponto de fixação do motor/, 'Fixações que unem o motor ao chassi; o motor é parte da estrutura e sustenta o câmbio e a suspensão traseira.',
  'O motor é estrutural desde os anos 1960: sem ele o carro se dobraria ao meio. Cada prisioneiro é torqueado em sequência definida.'),
 R(/^Pino de fixação do nariz|^Pino de retenção do nariz/, 'Pinos que prendem o nariz destacável ao chassi, permitindo a troca em segundos após um toque.',
  'A troca de nariz leva menos de 10 segundos; os pinos são projetados para resistir à carga aerodinâmica mas não impedir o colapso do cone.'),
 R(/^Inserto de suspensão|^Ponto de suspensão/, 'Insertos metálicos laminados dentro do carbono onde os braços da suspensão são fixados.',
  'Os insertos em titânio são colados dentro do laminado antes da cura, porque furar carbono depois enfraqueceria a estrutura.'),
 R(/^Torre do balancim|^Suporte do balancim/, 'Estrutura que sustenta o balancim da suspensão sobre o chassi, transmitindo as cargas do push-rod para molas e amortecedores.',
  'Fica escondida sob a tampa do nariz; abrir essa tampa é o primeiro passo para ajustar a suspensão dianteira nos boxes.'),
 R(/^Prancha|^Plank|^Patim|^Skid/, 'Prancha de madeira composta sob o assoalho que limita a altura de rodagem: se desgastar além de 1 mm, o carro é desclassificado.',
  'É feita de Jabroc, um compensado de faia impregnado em resina. Os patins de titânio geram as faíscas vistas à noite.'),
 R(/^Placa do chassi|^Placa de identificação/, 'Placa de identificação do chassi exigida pela homologação.', 'Cada chassi tem numeração própria; a FIA acompanha a história de cada um até a aposentadoria.'),

 // ---------------------------------------------------------------- suspensão
 R(/^Wishbone|^Braço superior|^Braço inferior|^Triângulo/, 'Braços em forma de asa que ligam a roda ao chassi e definem a geometria da suspensão; têm perfil aerodinâmico para não perturbar o ar.',
  'São ocos, de fibra de carbono, e mais rígidos que aço no mesmo peso; a espessura do perfil é limitada por regra para não virarem asas.'),
 R(/^Upright|^Manga de eixo|^Porta-cubo/, 'Peça usinada que segura o cubo da roda, o disco de freio e a pinça, e liga tudo aos braços da suspensão.',
  'Usinada de um bloco de titânio ou alumínio, ela também canaliza o ar de refrigeração dos freios por dentro.'),
 R(/^Push-rod|^Pull-rod|^Pushrod|^Pullrod/, 'Haste que transmite o movimento da roda ao balancim dentro do chassi, onde ficam molas e amortecedores.',
  'Push-rod empurra o balancim para cima; pull-rod puxa para baixo. A escolha depende de onde a equipe quer o centro de gravidade e o fluxo de ar.'),
 R(/^Balancim|^Rocker/, 'Alavanca que converte o movimento da haste em compressão da barra de torção, do amortecedor e do elemento de heave.',
  'A geometria do balancim define a progressividade da suspensão sem trocar molas; as equipes têm dezenas de balancins de relações diferentes.'),
 R(/^Barra de torção|^Torsion bar/, 'Mola em forma de barra que trabalha em torção; substitui a mola helicoidal porque ocupa menos espaço e é mais leve.',
  'A rigidez é escolhida trocando barras de diâmetros diferentes, um trabalho de minutos que muda o comportamento do carro.'),
 R(/^Amortecedor|^Damper/, 'Amortecedor hidráulico que controla a velocidade do movimento da suspensão, evitando oscilações do assoalho.',
  'Os amortecedores giratórios ou lineares têm ajustes de baixa e alta velocidade separados; sob o efeito solo, controlar o assoalho é a prioridade.'),
 R(/^Elemento de heave|^Heave|^Belleville|^Mola de prato/, 'Mola e amortecedor centrais que só atuam quando as duas rodas sobem juntas, controlando a altura do assoalho sem alterar a rolagem.',
  'As molas de prato Belleville permitem rigidez altíssima em pouco espaço, algo necessário para segurar o assoalho a milímetros do chão.'),
 R(/^Barra estabilizadora|^Anti-roll|^ARB/, 'Barra que liga os dois lados da suspensão e resiste à rolagem do carro em curva sem endurecer o movimento vertical.',
  'A troca de barra estabilizadora muda o equilíbrio entre subesterço e sobre-esterço e é um dos ajustes mais comuns entre treinos.'),
 R(/^Rótula|^Terminal esférico|^Uniball/, 'Articulação esférica de precisão que permite o movimento dos braços sem folga.', 'As rótulas são trocadas com frequência porque a menor folga muda a geometria e faz o carro perder confiança na frenagem.'),

 // ---------------------------------------------------------------- direção
 R(/^Cremalheira|^Caixa de direção|^Carcaça da cremalheira/, 'Caixa de direção com pinhão e cremalheira que converte o giro do volante em deslocamento lateral das barras de direção.',
  'A relação é tão direta que menos de meia volta de volante vira as rodas ao máximo; a assistência hidráulica alivia o esforço.'),
 R(/^Coifa da cremalheira|^Ponta da cremalheira/, 'Proteção sanfonada e extremidades da cremalheira que se movem com as barras de direção.', 'As coifas mantêm a graxa dentro e a poeira fora em uma peça que trabalha a centímetros do asfalto.'),
 R(/^Barra de direção|^Track rod/, 'Barra que liga a cremalheira ao braço da manga de eixo e efetivamente vira a roda.', 'Tem perfil aerodinâmico e é alinhada com o wishbone para não perturbar o ar; sua posição define o efeito Ackermann.'),
 R(/^Pinhão/, 'Engrenagem no fim da coluna que engrena na cremalheira.', 'Alguns carros usam pinhão de passo variável, tornando a direção mais direta conforme o volante gira.'),
 R(/^Servo|^Assistência hidráulica|^Válvula de assistência|^Linha hidráulica da direção/, 'Assistência hidráulica que reduz o esforço no volante; é alimentada pela bomba hidráulica do motor e limitada por regra a apenas ajudar, não a dirigir.',
  'A direção elétrica é proibida; a hidráulica tem de ser puramente proporcional ao esforço do piloto, sem qualquer função de estabilidade.'),
 R(/^Coluna de direção|^Junta universal|^Cardã da coluna/, 'Coluna em dois tramos com juntas universais que contorna os pés do piloto e liga o volante à cremalheira.',
  'A coluna é projetada para se dobrar em impacto e é uma das peças mais vigiadas nos testes de choque frontal.'),

 // ---------------------------------------------------------------- freios
 R(/^Disco carbono-carbono/, 'Disco de freio em carbono reforçado com carbono, ventilado por mais de mil furos radiais; trabalha entre 400 e 1000 °C.',
  'Leva meses para ser fabricado em fornos de deposição de carbono; pesa menos de 1,5 kg e para o carro de 300 a 0 em cerca de 4 segundos.'),
 R(/^Campana|^Bell do disco/, 'Campana de alumínio ou titânio que liga o disco ao cubo permitindo dilatação térmica.', 'O disco flutua na campana por pinos: ele cresce alguns milímetros quando quente e não pode ficar preso.'),
 R(/^Pino flutuante|^Pinos do disco/, 'Pinos que transmitem o torque do disco à campana enquanto permitem a dilatação térmica.', 'Molas de aço mantêm o disco centrado quando frio; ao aquecer o disco se expande e os pinos deslizam.'),
 R(/^Cubo|^Porca central|^Porca da roda/, 'Cubo da roda e porca única que prende a roda; a porca é apertada em menos de um segundo pela pistola pneumática.',
  'A porca tem sistema de retenção que a impede de soltar e um sensor que confirma o aperto antes de o carro ser liberado.'),
 R(/^Pinça monobloco|^Pinça/, 'Pinça de freio usinada em bloco único de alumínio-lítio com seis pistões; comprime as pastilhas contra o disco.',
  'Custa mais que um carro popular e é tão rígida que a folga no pedal quase não muda com a temperatura.'),
 R(/^Pistão da pinça|^Pistões/, 'Pistões de titânio que empurram as pastilhas; o titânio isola o calor do fluido de freio.', 'Pistões de tamanhos diferentes na mesma pinça equalizam o desgaste ao longo da pastilha.'),
 R(/^Pastilha/, 'Pastilha de carbono que atrita contra o disco; o coeficiente de atrito sobe com a temperatura, ao contrário dos freios de rua.',
  'Frias, quase não freiam. Por isso os pilotos zigue-zagueiam e freiam forte na volta de apresentação.'),
 R(/^Sangrador|^Bleed/, 'Parafuso de sangria por onde se retira o ar do circuito hidráulico.', 'A sangria é feita depois de cada troca de pinça, com o fluido aquecido para eliminar bolhas.'),
 R(/^Tambor|^Duto de freio|^Scoop|^Captação de ar de freio/, 'Duto e tambor que capturam ar para resfriar disco e pinça e controlam o calor transferido para o aro e o pneu.',
  'O calor do freio é usado de propósito para aquecer o pneu pela roda; o tamanho do duto muda de circuito para circuito.'),
 R(/^Sensor infravermelho|^Sensor de temperatura do disco/, 'Sensor infravermelho que mede a temperatura do disco sem contato.', 'Os dados vão ao volante: o piloto vê se está queimando o freio e adapta a frenagem.'),
 R(/^Gravação INTEIA na pinça/, 'Identidade do laboratório gravada na pinça.', 'Nas pinças reais aparece o nome do fabricante, geralmente Brembo ou AP Racing.'),
 R(/^Pedal de freio|^Braço do pedal de freio|^Alívio de massa|^Nervura antiderrapante/, 'Pedal de freio operado com o pé esquerdo, sem assistência: o piloto aplica mais de 150 kg de força em cada frenagem forte.',
  'É quase rígido e responde à pressão, não ao curso. Os pilotos treinam a perna esquerda porque a musculatura decide a consistência da frenagem.'),
 R(/^Cilindro mestre/, 'Dois cilindros mestres, um por circuito, que convertem a força do pedal em pressão hidráulica para dianteira e traseira separadamente.',
  'Cilindros de diâmetros diferentes mudam o balanço básico; a barra entre eles é o ajuste fino comandado do volante.'),
 R(/^Barra de balanço|^Bias bar/, 'Barra basculante entre os cilindros mestres que distribui a força do pedal entre dianteira e traseira.',
  'Girar o ajuste um clique move o ponto de apoio décimos de milímetro e desloca cerca de 1% do balanço.'),
 R(/^Unidade brake-by-wire|^Brake-by-wire|^Atuador traseiro/, 'Sistema eletrônico do freio traseiro: combina a frenagem regenerativa do MGU-K com a hidráulica para o pedal ter sempre a mesma sensação.',
  'Sem ele, o piloto sentiria o freio mudar cada vez que a bateria enchesse; se o sistema falha, um circuito hidráulico de reserva assume.'),
 R(/^Linha rígida|^Mangueira trançada|^Fluido de freio/, 'Tubulação do circuito hidráulico: linhas rígidas ao longo do chassi e mangueiras trançadas flexíveis até as pinças que se movem com a roda.',
  'O fluido trabalha acima de 300 °C sem ferver; as mangueiras têm malha de aço para não inchar sob 100 bar de pressão.'),

 // ---------------------------------------------------------------- unidade de potência
 R(/^Bloco do motor|^Cárter|^Bandeja de óleo|^Nervura do bloco/, 'Bloco do V6 de 1,6 litro a 90°, em alumínio, com cárter seco; é estrutural e liga o chassi ao câmbio.',
  'O ângulo de 90° e a cilindrada são fixados por regra; o bloco pesa menos de 30 kg mas suporta o carro inteiro nas curvas.'),
 R(/^Cabeçote|^Tampa de comando|^Comando de válvulas|^Came/, 'Cabeçotes com dois comandos por bancada e válvulas pneumáticas, que permitem girar a 15 mil rpm sem molas metálicas.',
  'As válvulas fecham por ar comprimido, tecnologia da Renault dos anos 1980; molas de aço não acompanhariam essa rotação.'),
 R(/^Bobina|^Vela/, 'Ignição por bobina individual e vela por cilindro; a queima é iniciada em pré-câmara para propagar mais rápido.',
  'A pré-câmara de ignição por jato, vinda de motores estacionários, foi um dos segredos da eficiência térmica acima de 50%.'),
 R(/^Injetor|^Rampa de combustível|^Flauta/, 'Injetores diretos de alta pressão que dosam o combustível dentro do cilindro; a pressão é limitada a 500 bar.',
  'O regulamento limita o fluxo a 100 kg/h, então cada gota tem de virar potência; em 2026 o combustível é 100% sustentável.'),
 R(/^Compressor|^Voluta do compressor|^Rotor do compressor/, 'Compressor do turbo, montado na frente do motor: comprime o ar admitido antes de ele ir ao intercooler.',
  'Em algumas unidades o compressor fica a quase um metro da turbina, ligados por um eixo que atravessa o V do motor.'),
 R(/^Turbina|^Voluta da turbina|^Rotor da turbina/, 'Turbina movida pelos gases de escape; gira o eixo que aciona o compressor e, até 2025, o MGU-H.',
  'Gira acima de 100 mil rpm com gases a 1000 °C; o rotor é de liga de níquel fundida em molde de cera perdida.'),
 R(/^Eixo do turbo|^Eixo comum/, 'Eixo que liga turbina e compressor através do V do motor.', 'Além de transmitir o giro, o eixo era onde o MGU-H se acoplava para gerar energia ou eliminar o atraso do turbo.'),
 R(/^MGU-H/, 'Motor-gerador ligado ao turbo: recupera energia do calor do escape e acelera o compressor para eliminar o atraso de resposta.',
  'A peça mais cara e complexa da unidade de potência. Foi eliminada em 2026 para atrair novos fabricantes, e o MGU-K dobrou de potência para compensar.'),
 R(/^Primário de escape|^Coletor de escape|^Coletor/, 'Tubos primários em Inconel que levam os gases de cada cilindro ao coletor e à turbina; os comprimentos são iguais para equilibrar os pulsos.',
  'O tom de cor azul-dourado é a pátina de óxido do Inconel a 900 °C; os tubos têm parede de menos de 1 mm.'),
 R(/^Tubo da wastegate|^Wastegate|^Válvula de alívio/, 'Válvula que desvia gases da turbina para controlar a pressão do turbo; as saídas ficam ao lado do escapamento.',
  'Com o MGU-H, a pressão era controlada eletricamente e a wastegate quase não abria; em 2026 ela volta a trabalhar o tempo todo.'),
 R(/^Escapamento|^Tailpipe|^Saída de escape/, 'Saída única do escapamento, na traseira, cujo posicionamento é fixado por regra para não soprar a asa.',
  'O som mais grave dos motores híbridos vem daqui: a turbina absorve energia dos gases e abafa o ruído.'),
 R(/^Snorkel|^Duto do airbox|^Entrada de ar do motor/, 'Duto que leva o ar do airbox acima do piloto ao compressor.', 'O airbox usa a pressão dinâmica do ar a 300 km/h para pré-comprimir a admissão, um efeito que vale alguns cavalos.'),
 R(/^Duto de carga|^Duto de ar comprimido/, 'Dutos que levam o ar comprimido do compressor ao intercooler e de volta aos plenums.',
  'Ar comprimido a 3,5 bar chega a 200 °C; sem o intercooler perderia densidade e o motor detonaria.'),
 R(/^Plenum de admissão/, 'Câmara de admissão sobre cada bancada, com trompetas de comprimento variável para cada cilindro.',
  'O plenum é de carbono e suporta a explosão em caso de retorno de chama; as trompetas sobem e descem para afinar o motor a cada rotação.'),
 R(/^Trompeta/, 'Trompetas de admissão de comprimento variável que ajustam a ressonância do ar à rotação do motor.',
  'São movidas por atuador hidráulico em milissegundos; a variação vale torque em toda a faixa de rotação.'),
 R(/^Bomba de água|^Bomba de óleo|^Alternador|^Acessório|^Correia|^Bomba hidráulica/, 'Acessórios acionados pelo motor: bombas de água, óleo e hidráulica, todas movidas por engrenagens e não por correias.',
  'Nada de correias: as engrenagens não escorregam e permitem posicionar cada bomba onde o pacote aerodinâmico pede.'),
 R(/^Ar de admissão|^Ar comprimido|^Ar resfriado|^Gases de escape/, 'Fita ilustrativa do caminho do ar e dos gases: airbox, compressor, intercooler, plenums, cilindros, turbina e escapamento.',
  'Do airbox ao escapamento, o ar leva menos de um décimo de segundo e chega a 1000 °C.'),

 // ---------------------------------------------------------------- ERS
 R(/^Energy store|^Módulo de células|^Terminal do módulo|^Barramento de cobre|^Unidade de monitoramento das células|^Contator/, 'Bateria de íon-lítio sob o tanque de combustível: armazena a energia recuperada e a devolve ao MGU-K; pesa entre 20 e 25 kg.',
  'Pode entregar e absorver 4 MJ por volta; as células são refrigeradas por placa fria e monitoradas uma a uma pela FIA.'),
 R(/^Conector de alta tensão|^Cabo de alta tensão/, 'Cabos e conectores laranja de alta tensão, em torno de 800 V, que ligam bateria, inversor e motores elétricos.',
  'O laranja é padrão internacional de alta tensão; os mecânicos usam luvas isolantes e o carro exibe um LED verde quando é seguro tocar.'),
 R(/^Eletrônica de controle|^Inversor|^Aleta do inversor|^Conector de dados do inversor/, 'Inversor que converte a corrente contínua da bateria em alternada para o MGU-K e vice-versa, milhares de vezes por segundo.',
  'Usa transistores de carbeto de silício e é refrigerado a água; a eficiência supera 97%.'),
 R(/^Conversor DC-DC/, 'Conversor que abaixa a alta tensão para os 12 V da eletrônica e das bombas do carro.', 'Substitui o alternador convencional; se falhar, o carro para por falta de energia para a eletrônica.'),
 R(/^MGU-K|^Trem de engrenagens do MGU-K|^Carcaça do trem|^Conector trifásico/, 'Motor-gerador ligado ao virabrequim: freia o carro recuperando energia e devolve potência na aceleração.',
  'Passa de 120 kW para 350 kW em 2026, quase igualando o motor a combustão; ele também faz o papel de motor de partida.'),
 R(/^Recuperação|^Entrega|^Energia /, 'Fita ilustrativa do fluxo de energia: recuperação na frenagem para a bateria e entrega na aceleração.',
  'Em uma volta o sistema recupera energia suficiente para acender uma casa por horas, tudo em frenagens de poucos segundos.'),

 // ---------------------------------------------------------------- refrigeração
 R(/^Intercooler/, 'Trocador ar-ar que resfria o ar comprimido pelo turbo antes de ele entrar no motor, aumentando a densidade e a potência.',
  'Fica inclinado no sidepod para caber mais área no pacote estreito; algumas equipes usam intercooler água-ar montado no V do motor.'),
 R(/^Radiador de água/, 'Radiador principal do circuito de água do motor, no sidepod; rejeita boa parte do calor gerado pela combustão.',
  'As aletas têm menos de 0,1 mm e são tão delicadas que os radiadores viajam em caixas próprias e são tapados com fita antes da largada.'),
 R(/^Arrefecedor de óleo do motor/, 'Trocador que resfria o óleo do motor, que lubrifica e também retira calor dos pistões.', 'O óleo chega a 150 °C; jatos sob os pistões o usam para refrigerar a coroa.'),
 R(/^Arrefecedor de óleo do câmbio/, 'Trocador que resfria o óleo do câmbio e do sistema hidráulico.', 'O câmbio dissipa dezenas de quilowatts em atrito; sem esse trocador o óleo se degradaria em poucas voltas.'),
 R(/^Arrefecedor de baixa temperatura do ERS/, 'Trocador dedicado ao circuito de baixa temperatura que resfria bateria, inversor e MGU-K.', 'A bateria precisa ficar abaixo de 60 °C, muito menos que o motor; por isso tem circuito de água próprio.'),
 R(/^Tanque de expansão|^Tampa pressurizada/, 'Tanque que absorve a dilatação do líquido de arrefecimento e separa o ar do circuito; a tampa mantém o sistema pressurizado.',
  'A 3,5 bar a água ferve acima de 140 °C, e o motor pode trabalhar mais quente, com radiadores menores e menos arrasto.'),
 R(/^Abraçadeira/, 'Abraçadeira que fixa a mangueira ao bocal do trocador.', 'São de liga leve e apertadas com torque medido; uma mangueira solta encerra a corrida em segundos.'),
 R(/^Água ·|^Óleo do motor ·|^Óleo do câmbio ·|^Hidráulica ·|^ERS ·|^Ar de arrefecimento/, 'Mangueira ou fita ilustrativa dos circuitos de água, óleo e hidráulica entre motor, câmbio e trocadores nos sidepods.',
  'Cada circuito tem temperatura própria: água do motor a 120 °C, óleo a 150 °C e circuito do ERS abaixo de 60 °C.'),
 R(/^Boca do sidepod/, 'Entrada de ar do sidepod que alimenta os trocadores; seu tamanho é um compromisso entre refrigeração e arrasto.',
  'Em circuitos quentes as equipes abrem saídas extras na carroceria; cada centímetro quadrado a mais custa velocidade na reta.'),

 // ---------------------------------------------------------------- combustível
 R(/^Bexiga flexível|^Célula de combustível/, 'Tanque flexível em Kevlar e borracha, montado entre o piloto e o motor; deforma sem romper em acidente.',
  'Tem cerca de 110 litros e é feito pelos mesmos fabricantes dos tanques de helicóptero militar; é enfiado no chassi por uma abertura pequena e inflado por dentro.'),
 R(/^Combustível · volume|^Combustível \(|^Nível de combustível/, 'Representação do combustível dentro da célula.', 'Sem reabastecimento desde 2010, o carro larga com 100 kg de combustível e o consumo é planejado volta a volta.'),
 R(/^Chicana|^Defletor interno|^Baffle/, 'Divisórias internas que impedem o combustível de balançar nas curvas e garantem que ele fique junto da captação.',
  'Com 5 g laterais, 100 kg de combustível se comportam como uma onda; as chicanas evitam falta de alimentação e mudanças bruscas de equilíbrio.'),
 R(/^Pote de turbilhonamento|^Coletor de combustível|^Swirl pot/, 'Pequeno reservatório sempre cheio de onde a bomba de alta pressão aspira, mesmo com o tanque quase vazio.',
  'É o motivo de o carro conseguir terminar a corrida com menos de um litro no tanque.'),
 R(/^Bomba de elevação|^Linha da bomba de elevação/, 'Bombas elétricas de baixa pressão que levam combustível do fundo da célula ao pote coletor.', 'Trabalham submersas no combustível, que as refrigera; há mais de uma para redundância.'),
 R(/^Bomba de alta pressão|^Bomba mecânica/, 'Bomba mecânica que eleva a pressão a até 500 bar para os injetores diretos.', 'É acionada pelo comando de válvulas e é uma das peças com tolerâncias mais finas do motor.'),
 R(/^Medidor de fluxo|^Fluxímetro/, 'Sensor ultrassônico homologado pela FIA que mede o fluxo de combustível; o limite é 100 kg/h.',
  'Foi a solução para limitar potência sem limitar rotação; violá-lo em 2014 custou à Red Bull a desclassificação de Ricciardo na Austrália.'),
 R(/^Linha de alimentação|^Linha de retorno|^Combustível ·/, 'Linhas de combustível entre célula, bombas, medidor e motor, com fita ilustrativa do fluxo.',
  'As linhas têm válvulas de corte automático que fecham se o motor se separar do chassi em um acidente.'),
 R(/^Bocal de reabastecimento|^Acoplamento de reabastecimento/, 'Acoplamento de engate rápido por onde a equipe abastece e drena o tanque na garagem.',
  'Mesmo sem reabastecimento em corrida, o bocal é regulamentado: a FIA drena um litro após a prova para análise do combustível.'),
 R(/^Cinta da célula|^Cinta de fixação/, 'Cintas que prendem a célula ao chassi.', 'A célula é mole; sem as cintas ela se deslocaria a cada frenagem.'),

 // ---------------------------------------------------------------- transmissão
 R(/^Carcaça do câmbio|^Janela/, 'Carcaça estrutural do câmbio, em titânio fundido ou carbono, que sustenta a suspensão traseira e a estrutura de impacto.',
  'Deve durar seis fins de semana consecutivos por regra. A janela desta maquete é apenas para estudo das engrenagens.'),
 R(/^Embreagem|^Disco de embreagem|^Placa de pressão|^Atuador da embreagem/, 'Embreagem multidisco de carbono de apenas 100 mm de diâmetro, acionada hidraulicamente pelas borboletas do volante.',
  'Suporta 1000 cv com discos do tamanho de um pires porque o carbono mantém atrito mesmo a 500 °C.'),
 R(/^Eixo primário|^Eixo de entrada|^Eixo secundário|^Eixo de saída/, 'Eixos do câmbio: o primário recebe o torque do motor e o secundário entrega à coroa e ao diferencial.',
  'São ocos e curtos; o câmbio inteiro tem o comprimento de um antebraço e pesa cerca de 40 kg.'),
 R(/^Engrenagem da \d|^Par de engrenagens|^Engrenagem intermediária da ré|^Engrenagem/, 'Um dos oito pares de engrenagens sempre engrenados; a marcha é selecionada travando a engrenagem ao eixo com anéis de dentes.',
  'As relações são congeladas para a temporada; as engrenagens de aço cementado são trocadas após cada corrida.'),
 R(/^Anel de dentes|^Dog ring|^Luva de engate/, 'Anel com dentes retos que trava a engrenagem ao eixo sem sincronizador, permitindo trocas quase instantâneas.',
  'A troca sem corte acontece porque o anel da marcha seguinte engata antes de o anterior soltar; o motor nem percebe.'),
 R(/^Tambor seletor|^Garfo seletor/, 'Tambor cilíndrico com ranhuras que move os garfos e os anéis de dentes; gira acionado por hidráulica.',
  'Uma volta parcial do tambor troca a marcha em menos de 30 ms; ele impede que duas marchas sejam engatadas ao mesmo tempo.'),
 R(/^Pinhão de ataque|^Coroa/, 'Pinhão e coroa cônicos que viram o torque em 90° para os semieixos e definem a relação final.',
  'A relação final é escolhida por circuito conforme a velocidade máxima esperada na reta.'),
 R(/^Diferencial|^Satélite|^Planetária|^Caixa do diferencial/, 'Diferencial que permite às rodas traseiras girarem em velocidades diferentes em curva; o travamento é controlado hidraulicamente.',
  'O piloto ajusta o travamento no volante para entrada, meio e saída de curva; mais travado dá tração, menos travado dá rotação.'),
 R(/^Junta tripóide|^Copo da junta|^Rolete da tripóide|^Coifa da junta/, 'Junta homocinética que permite ao semieixo transmitir torque enquanto a suspensão se move.',
  'Trabalha com ângulos pequenos porque a suspensão traseira quase não se move; a coifa segura a graxa a 15 mil rpm.'),
 R(/^Semieixo|^Driveshaft/, 'Semieixo tubular que leva o torque do diferencial à roda.', 'De aço ou compósito, é dimensionado para torcer alguns graus sob carga e amortecer as trocas de marcha.'),
 R(/^Flange de saída/, 'Flange do diferencial onde o semieixo se acopla.', 'Gira à rotação da roda; esta maquete o anima na relação correta com as engrenagens.'),
 R(/^Torque ·/, 'Fita ilustrativa do caminho do torque: motor, embreagem, marchas, coroa, diferencial e semieixos.', 'Do virabrequim à roda, o torque é multiplicado mais de dez vezes na primeira marcha.'),

 // ---------------------------------------------------------------- sensores
 R(/^Tubo de Pitot|^Pitot/, 'Sonda que mede a velocidade real do ar em relação ao carro, dado essencial para a aerodinâmica e o controle de potência.',
  'A mesma tecnologia dos aviões; em treinos livres os carros levam grades com dezenas de sondas Pitot para mapear o fluxo.'),
 R(/^Anel fônico|^Roda fônica|^Sensor de rotação da roda/, 'Anel dentado e sensor que medem a rotação de cada roda para controle de tração, ABS de aquisição de dados e telemetria.',
  'Controle de tração é proibido, mas o dado alimenta o brake-by-wire e a estratégia de energia.'),
 R(/^Câmera infravermelha|^Câmera térmica/, 'Câmeras infravermelhas que medem a temperatura da superfície dos pneus em tempo real, por faixas da banda de rodagem.',
  'Mostram ao engenheiro se o pneu está aquecendo por dentro ou por fora e orientam ajustes de câmber e pressão.'),
 R(/^Sensor laser de altura|^Altura de rodagem/, 'Sensor laser que mede a distância do assoalho ao chão, dado central para o efeito solo.',
  'Milímetros mudam o downforce; as equipes comparam os sensores dos dois lados para detectar rolagem e desgaste da prancha.'),
 R(/^ECU|^Unidade de controle/, 'Unidade de controle padronizada da FIA, fornecida pela McLaren Applied, que gerencia motor, câmbio, ERS e aquisição de dados.',
  'É a mesma para todas as equipes e roda um software auditado; grava mais de mil canais e envia telemetria ao muro e à FIA.'),
 R(/^ADR|^Gravador de acidentes|^Caixa preta/, 'Gravador de dados de acidente da FIA: registra acelerações e sinais do carro para investigação de choques.',
  'Junto com o acelerômetro no ouvido do piloto, permitiu à FIA melhorar barreiras, Halo e cintos com base em dados reais.'),
 R(/^IMU|^Unidade inercial|^Giroscópio/, 'Unidade inercial que mede acelerações e rotações do carro nos três eixos.', 'Seus dados alimentam a análise de rolagem, arfagem e o cálculo de forças que o piloto suporta, acima de 5 g.'),
 R(/^Transceptor|^Antena|^Telemetria/, 'Transceptor e antena de telemetria que enviam os dados do carro aos boxes em tempo real.',
  'A telemetria é só de ida: desde 2003, os boxes não podem alterar nada no carro remotamente.'),
 R(/^Célula de carga/, 'Sensor de força montado na haste da suspensão que mede a carga vertical em cada roda.', 'É assim que se mede o downforce na pista: a diferença de carga com e sem velocidade.'),
 R(/^Termopar/, 'Termopar que mede temperaturas de escape, óleo e água.', 'O escape passa de 1000 °C; os termopares são de platina e trocados com frequência.'),
 R(/^Chicote|^Loom|^Cabo de dados|^Dados ·/, 'Chicote elétrico que liga sensores, atuadores e a ECU; um carro tem mais de um quilômetro de fios.',
  'Os chicotes são feitos à mão, com conectores aeronáuticos, e pesam mais que o volante inteiro.'),
];

const SYSTEM_FALLBACK = {
 aero: ['Elemento aerodinâmico que orienta ou acelera o ar em torno do carro para gerar carga e reduzir arrasto.', 'Um F1 moderno gera mais de três vezes o próprio peso em carga aerodinâmica a 250 km/h.'],
 structure: ['Elemento estrutural da célula de sobrevivência ou de seu entorno.', 'A célula de carbono passa por ensaios de impacto a até 15 m/s e ensaios estáticos de 25 toneladas.'],
 suspension: ['Elemento da suspensão que controla o movimento da roda e a altura do assoalho.', 'A suspensão de um F1 se move poucos centímetros; a maior parte do conforto vem da flexão do pneu.'],
 steering: ['Elemento do sistema de direção.', 'O volante gira menos de meia volta de batente a batente.'],
 brakes: ['Elemento do sistema de freios de carbono.', 'A frenagem de 300 km/h a zero leva cerca de 4 segundos e 130 metros, com desaceleração acima de 5 g.'],
 power: ['Elemento da unidade de potência híbrida V6 turbo de 1,6 litro.', 'A unidade de potência supera 50% de eficiência térmica, contra cerca de 30% de um carro de rua.'],
 ers: ['Elemento do sistema de recuperação de energia.', 'Em 2026 quase metade da potência total vem do sistema elétrico.'],
 cooling: ['Elemento do sistema de refrigeração.', 'Os trocadores rejeitam mais de 100 kW de calor em corrida, o equivalente a dezenas de aquecedores domésticos.'],
 fuel: ['Elemento do sistema de combustível.', 'O carro larga com até 110 kg de combustível sustentável e o consumo é gerido volta a volta.'],
 transmission: ['Elemento do câmbio sequencial de oito marchas e do diferencial.', 'O câmbio troca marchas em menos de 50 milissegundos sem cortar a aceleração.'],
 safety: ['Elemento do sistema de segurança do carro.', 'Desde 1994, cada acidente grave gera uma mudança de regra: Halo, HANS, cabos de retenção e barreiras nasceram assim.'],
 cockpit: ['Elemento do cockpit e da retenção do piloto.', 'O piloto fica quase deitado, com os pés acima do quadril, para o carro ter nariz baixo.'],
 wheel: ['Comando do volante.', 'Um volante moderno tem mais de 20 botões, seis seletores e centenas de combinações possíveis.'],
 sensors: ['Sensor ou unidade eletrônica de aquisição de dados.', 'Cada carro grava mais de mil canais e envia gigabytes de dados por fim de semana.'],
};

export function describePart(part, systemId) {
 const hit = RULES.find((rule) => rule.pattern.test(part));
 if (hit) return {funcao: hit.funcao, curiosidade: hit.curiosidade, generico: false};
 const fb = SYSTEM_FALLBACK[systemId] || ['Peça do sistema.', ''];
 return {funcao: fb[0], curiosidade: fb[1], generico: true};
}

export const PARTS_INFO_RULES = RULES.length;


// ---------------------------------------------------------------- componentes externos do carro (bancada Carro)
const CAR_RULES = [
 R(/^Carroceria/, 'Casca de carbono que envolve a célula de sobrevivência, o motor e os sidepods; dá a forma aerodinâmica ao carro e protege os sistemas internos.',
  'A carroceria é trocada várias vezes por temporada conforme as atualizações aerodinâmicas; cada painel pesa poucos quilos e é ajustado ao milímetro.'),
 R(/^Flap traseiro DRS/, 'Flap móvel da asa traseira: em posição fechada gera carga; aberto, reduz o arrasto e libera velocidade na reta.',
  'A abertura vale de 10 a 15 km/h no fim da reta. Em 2026 o sistema dá lugar à aerodinâmica ativa, que move as duas asas.'),
 R(/^Asa traseira principal/, 'Plano principal da asa traseira, que gera a maior parte da carga do eixo traseiro e é a maior fonte de arrasto do carro.',
  'Em Monza a asa é quase plana; em Mônaco, o mais inclinada possível. A escolha muda a velocidade final em dezenas de km/h.'),
 R(/^Placa lateral traseira/, 'Placa vertical na ponta da asa traseira que impede o ar de escapar pela lateral e mantém a diferença de pressão entre as faces da asa.',
  'As bordas recortadas geram vórtices controlados que reduzem o arrasto induzido, o mesmo princípio dos winglets dos aviões.'),
 R(/^Suporte (superior|inferior) traseiro|^Suporte da asa traseira/, 'Pilares e suportes que prendem a asa traseira à estrutura de impacto e ao câmbio, transmitindo centenas de quilos de carga.',
  'A asa traseira empurra o carro para baixo com mais de 400 kg em alta velocidade; os pilares são ensaiados para não flexionar além do permitido.'),
 R(/^Suporte do DRS|^Mecanismo do DRS/, 'Atuador e articulações que abrem o flap traseiro por comando do piloto e o fecham ao tocar o freio.',
  'A abertura é hidráulica e leva menos de meio segundo; só é permitida em zonas definidas e a menos de um segundo do carro da frente.'),
 R(/^Placa lateral dianteira/, 'Placa lateral da asa dianteira que direciona o ar para fora da roda, reduzindo a turbulência que ela gera.',
  'O ar jogado para fora da roda dianteira é chamado de outwash; controlá-lo é um dos maiores temas do projeto aerodinâmico.'),
 R(/^Asa dianteira/, 'Elemento da asa dianteira: o primeiro a tocar o ar, gera carga no eixo dianteiro e organiza o fluxo para todo o resto do carro.',
  'O ângulo dos flaps é ajustado nos boxes com uma chave em poucos segundos e é o principal ajuste de equilíbrio durante a corrida.'),
 R(/^Suporte dianteiro|^Suporte da asa dianteira/, 'Pilares e suportes que ligam a asa dianteira ao nariz e sustentam os elementos entre si.',
  'Os pilares são desenhados para se romper de modo controlado em impacto, junto com o cone do nariz.'),
 R(/^Detalhe de flap dianteiro/, 'Ajustador e detalhes do flap dianteiro, onde o ângulo é regulado nos boxes.',
  'Um clique no ajustador muda o ângulo em frações de grau e desloca o equilíbrio do carro para a frente ou para trás.'),
 R(/^Assoalho/, 'Piso do carro que gera a maior parte da carga aerodinâmica pelo efeito solo, com túneis que aceleram o ar sob o carro.',
  'Alguns milímetros de altura em relação à pista mudam o comportamento inteiro do carro; é a peça mais sensível do projeto.'),
 R(/^Conjunto de roda/, 'Roda de magnésio forjado de 18 polegadas com porca única central e tampa aerodinâmica.',
  'A roda é trocada em menos de dois segundos e meio; a porca já vem presa ao aro para não cair durante a parada.'),
 R(/^Pneu dianteiro/, 'Pneu dianteiro; a borracha macia aquece rápido e gera a aderência lateral nas curvas.',
  'Um jogo dura poucas dezenas de voltas; a temperatura ideal fica entre 90 e 110 °C, medida por sensores infravermelhos.'),
 R(/^Pneu traseiro/, 'Pneu traseiro, mais largo que o dianteiro, que transmite a potência ao asfalto na aceleração.',
  'A patinagem na saída de curva é o que mais aquece e desgasta o pneu traseiro; por isso os pilotos dosam o acelerador com tanto cuidado.'),
 R(/^Cobertura interna/, 'Painel interno que fecha o vão entre a roda e a suspensão e controla o ar que sai dos freios.',
  'O calor dos freios é usado para aquecer o pneu pelo aro; esses painéis regulam quanto calor passa para a roda.'),
 R(/^Suspensão (dianteira|traseira)/, 'Wishbones em perfil de asa que ligam a roda ao chassi e definem a geometria da suspensão.',
  'Além de sustentar a roda, eles orientam o ar em direção ao assoalho; a forma é limitada por regra para não virarem asas.'),
 R(/^Haste dianteira/, 'Push-rod: haste que transmite o movimento da roda ao balancim dentro do chassi, onde ficam molas e amortecedores.',
  'Colocar molas e amortecedores dentro do chassi limpa o fluxo de ar em volta da roda; a haste trabalha só em compressão.'),
 R(/^Conjunto de eixo traseiro/, 'Semieixo que leva o torque do diferencial à roda traseira, com juntas homocinéticas nas duas pontas.',
  'É protegido por uma carenagem em perfil de asa para não perturbar o ar que vai ao difusor.'),
 R(/^Interior do cockpit/, 'Cavidade onde o piloto se senta, com a abertura definida por regra para permitir a saída em cinco segundos.',
  'O piloto sai do cockpit sem apoiar as mãos fora da célula; o exercício de evacuação é obrigatório e cronometrado.'),
 R(/^Defletor transparente/, 'Pequeno para-brisa que desvia o ar acima do capacete e reduz a turbulência sobre o piloto.',
  'Sem ele, a 300 km/h a corrente de ar empurraria o capacete para cima com força de vários quilos.'),
 R(/^Display do volante|^Indicadores do volante/, 'Tela e LEDs do volante onde o piloto lê marcha, tempos, temperaturas e o momento de trocar de marcha.',
  'A marcha aparece grande no centro porque é lida de relance na frenagem; os LEDs acendem em sequência com a rotação.'),
 R(/^Botões do volante/, 'Botões e seletores do volante: rádio, bebida, limitador de boxes, mapas de motor, energia e freio. Abra a bancada Sistemas para ler cada comando.',
  'Um volante moderno tem mais de 20 botões e seis seletores; o piloto opera tudo sem tirar as mãos das empunhaduras.'),
 R(/^Empunhadura do volante/, 'Empunhaduras moldadas à mão do piloto, na vertical porque o volante gira menos de meia volta.',
  'Atrás delas ficam as borboletas de marcha e de embreagem, acionadas com os dedos.'),
 R(/^Estrutura do volante/, 'Corpo de carbono do volante que abriga a eletrônica e sustenta todos os comandos.',
  'Custa em torno de 50 mil euros, pesa cerca de 1,3 kg e sai do carro em segundos pelo engate rápido.'),
 R(/^Conexão do volante/, 'Engate rápido e coluna que ligam o volante à cremalheira de direção.',
  'A coluna tem duas juntas universais para contornar os pés do piloto e é projetada para se dobrar em impacto.'),
 R(/^Luz traseira|^Conjunto de LEDs traseiros/, 'Luz vermelha obrigatória, acesa em chuva e piscando quando o carro recupera energia com o sistema híbrido.',
  'Pisca também quando o motor está em modo de recarga, avisando o carro de trás que a velocidade pode cair de repente.'),
 R(/^Escape/, 'Saída dos gases do motor depois da turbina, posicionada na traseira para não soprar a asa.',
  'O tubo é de Inconel e passa de 900 °C; o tom grave do motor híbrido vem da turbina absorvendo energia dos gases.'),
 R(/^Detalhe da tomada de ar/, 'Entrada de ar acima do piloto que alimenta o motor e abriga a estrutura principal de capotamento.',
  'A 300 km/h a pressão dinâmica na entrada pré-comprime o ar do motor, um efeito que vale alguns cavalos.'),
 R(/^Antena/, 'Antenas de telemetria, rádio e cronometragem, ao lado do cockpit e no nariz.',
  'A telemetria manda mais de mil canais de dados ao box em tempo real, mas nada pode ser enviado do box para o carro.'),
 R(/^Espelho retrovisor/, 'Espelho obrigatório que dá visão traseira ao piloto; a carenagem é desenhada para ajudar o fluxo em torno do sidepod.',
  'A área refletiva mínima é definida por regra; com a vibração, o piloto enxerga pouco mais que a posição do carro de trás.'),
];
const CAR_CATEGORY_FALLBACK = {
 body: ['Painel da carroceria de carbono que dá forma aerodinâmica ao carro e protege os sistemas internos.', 'Cada painel é feito em molde de autoclave e pesa poucos quilos.'],
 aero: ['Elemento aerodinâmico que orienta o ar e gera carga para o carro grudar na pista.', 'Um carro de Fórmula 1 gera mais de três vezes o próprio peso em carga aerodinâmica a 250 km/h.'],
 wheels: ['Componente do conjunto roda e pneu.', 'A troca das quatro rodas leva menos de dois segundos e meio.'],
 suspension: ['Componente da suspensão, que liga a roda ao chassi e controla a altura do assoalho.', 'A suspensão de um Fórmula 1 se move poucos centímetros; a maior parte do conforto vem da flexão do pneu.'],
 cockpit: ['Componente do cockpit, o espaço do piloto dentro da célula de sobrevivência.', 'O piloto fica quase deitado, com os pés acima do quadril, para o nariz do carro ser baixo.'],
 details: ['Detalhe externo do carro.', 'Cada detalhe visível passou por túnel de vento ou simulação antes de ir para a pista.'],
};
export function describeCarPart(label, category) {
 const hit = CAR_RULES.find((rule) => rule.pattern.test(label || ''));
 if (hit) return {funcao: hit.funcao, curiosidade: hit.curiosidade, generico: false};
 const fb = CAR_CATEGORY_FALLBACK[category] || ['Componente do carro.', ''];
 return {funcao: fb[0], curiosidade: fb[1], generico: true};
}
