import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';

// Catalog based on the chapters and corrections visible in the Animagraffs reference video.
// The geometry below is intentionally an original, explanatory layer rather than a copy of
// the video's artwork or a claim of homologation-level CAD accuracy.
export const SYSTEM_CATALOG=Object.freeze([
 {id:'aero',number:'01',label:'Aerodinâmica',short:'AERO',chapter:'0:14',color:'#52c8df',description:'Fluxo externo, underfloor, difusor e DRS aparecem separados como caminhos didáticos. A leitura mostra carga e menor arrasto de forma ilustrativa; não é CFD nem mistura DRS histórico com active aero 2026.'},
 {id:'structure',number:'02',label:'Estrutura central / survival cell didática',short:'ESTRUTURA',chapter:'4:47',color:'#c5a7ff',description:'A estrutura central / survival cell didática mostra anteparas, zonas de impacto e pontos de montagem. Motor, câmbio e suspensão são conectados externamente; não ficam contidos na célula e nada aqui é homologação.'},
 {id:'suspension',number:'03',label:'Suspensão',short:'SUSPENSÃO',chapter:'5:19',color:'#f1bd68',description:'Wishbones, upright, pushrod/pullrod, rocker, damper e torsion bar formam uma cadeia visual conectada. A amplitude animada, quando presente, é hipótese didática; não é cinemática real.'},
 {id:'steering',number:'04',label:'Direção',short:'DIREÇÃO',chapter:'7:52',color:'#ff8c6b',description:'Coluna, pinhão e rack-and-pinion mecânico ligam-se a track rods e uprights dianteiros. Linhas de assistência ficam separadas e esquemáticas; não representam direção hidráulica convencional nem torque real.'},
 {id:'brakes',number:'05',label:'Freios',short:'FREIOS',chapter:'8:57',color:'#ff665d',description:'Pedal, cilindros mestres, bias, linhas dianteiras/traseiras, discos, pinças e dutos formam dois caminhos didáticos. A contribuição regenerativa do MGU-K é separada; pressão e calor são apenas ilustrativos.'},
 {id:'power',number:'06',label:'Unidade de potência',short:'V6 TURBO',chapter:'11:32',color:'#ff9f58',description:'O V6 de alta rotação usa um monoturbo didático dividido em compressor frontal e turbina traseira ligados por eixo comum, com MGU-H legado 2021, wastegate, intercooler, dois plenums e seis velocity stacks representativas. Em 2026 o MGU-H é removido; a contagem e o material dos plenums/trompetas são hipótese: não são verificáveis neste frame.'},
 {id:'ers',number:'07',label:'ERS híbrido',short:'ERS',chapter:'14:14',color:'#ffe36b',description:'No modo padrão do vídeo, a arquitetura 2021 combina energy store, control electronics/inverter, MGU-K e MGU-H legado para recuperação e entrega de energia; o modo 2026 remove o MGU-H.'},
  {id:'cooling',number:'08',label:'Refrigeração',short:'COOLING',chapter:'14:54',color:'#66e0b2',description:'Configuração assimétrica hipotética: intercooler ar-ar no sidepod esquerdo e matriz de trocadores no direito. Circuitos esquemáticos separados atendem motor/óleo, ERS/bateria e hidráulica/câmbio; não é simulação térmica, de pressão ou vazão.'},
 {id:'fuel',number:'09',label:'Célula de combustível',short:'COMBUSTÍVEL',chapter:'15:39',color:'#e6c06d',description:'Uma única célula flexível/bladder compacta fica atrás do piloto, em contenção estrutural didática e à frente do câmbio, com baffles, bomba, sensor de pressão, válvula breakaway auto-selante e linha segura fora do cockpit; não é geometria homologada.'},
  {id:'transmission',number:'10',label:'Câmbio e diferencial',short:'TRANSMISSÃO',chapter:'16:42',color:'#b7c2cc',description:'A caixa didática mostra oito relações à frente + uma ré, eixos primário/secundário, diferencial e o caminho diferencial → junta tripóide esquemática → driveshaft. Engrenagens, juntas e movimentos são representativos; não declaram rolamentos ou relações reais.'},
 {id:'safety',number:'11',label:'Segurança',short:'SAFETY',chapter:'17:03',color:'#ff4d67',description:'Halo, estrutura primária de capotamento, crash structures, estruturas laterais e três cabos independentes por roda formam uma camada esquemática de proteção, não homologada.'},
 {id:'cockpit',number:'12',label:'Cockpit e retenção',short:'COCKPIT',chapter:'17:51',color:'#d9a8ff',description:'Banco, arnês de seis pontos, FHR/HANS, headrest, pedais e hidratação formam uma leitura esquemática do espaço do piloto; não representa homologação.'},
 {id:'wheel',number:'13',label:'Volante e comandos',short:'VOLANTE',chapter:'19:17',color:'#8db5ff',description:'Aro, display, LEDs, paddles, botões, coluna, cubo e quick-release mostram exemplos de comandos representados, sem simular uma ECU real.'},
 {id:'sensors',number:'14',label:'Sensores',short:'SENSORES',chapter:'22:11',color:'#7ee5f2',description:'Tubo de Pitot e sua pressão, ECU/unidade de aquisição, sensores locais, barramento e telemetria carro → box aparecem separados como esquema didático, não telemetria real.'}
]);
export const SYSTEM_IDS=Object.freeze(SYSTEM_CATALOG.map(system=>system.id));

export const SURVIVAL_CELL_LAYOUT=Object.freeze({center:Object.freeze([0,.50,.42]),size:Object.freeze([.80,.68,1.20])});
const LOCAL_SPIN_AXES=Object.freeze({x:Object.freeze([1,0,0]),y:Object.freeze([0,1,0]),z:Object.freeze([0,0,1])});
export const advanceLocalSpin=(quaternion,axis='y',angle=0)=>{const values=LOCAL_SPIN_AXES[axis];if(!values)throw new Error(`Eixo de rotação local inválido: ${axis}`);return quaternion.clone().multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(...values),angle)).normalize();};
export const POWER_FUEL_LAYOUT=Object.freeze({
 powerBlock:Object.freeze({center:Object.freeze([0,.49,-.75]),size:Object.freeze([.58,.34,.78])}),
 fuelCell:Object.freeze({center:Object.freeze([0,.46,-.28]),size:Object.freeze([.30,.22,.10])}),
 fuelContainment:Object.freeze({center:Object.freeze([0,.46,-.28]),size:Object.freeze([.42,.32,.14])}),
 energyStore:Object.freeze({center:Object.freeze([0,.18,-.28]),size:Object.freeze([.40,.16,.16])}),
 fuelPump:Object.freeze([.12,.49,-.28]),fuelPressureSensor:Object.freeze([0,.55,-.28]),fuelBreakaway:Object.freeze([.18,.49,-.28]),
 gearbox:Object.freeze({center:Object.freeze([0,.46,-1.48]),size:Object.freeze([.54,.36,.82])}),
 cockpitRegionZ:Object.freeze([.09,.87]),
 fuelRoute:Object.freeze([[.12,.49,-.28],[.14,.49,-.34],[.14,.53,-.44],[.17,.56,-.60],[.20,.55,-.72]])
});
export const SUSPENSION_LAYOUT=Object.freeze({
 front:Object.freeze({
  wishboneUpperInner:Object.freeze([.16,.51,1.60]),wishboneLowerInner:Object.freeze([.16,.33,1.18]),
  uprightLower:Object.freeze([.72,.27,1.30]),uprightUpper:Object.freeze([.72,.45,1.46]),rockerHigh:Object.freeze([.30,.62,1.02])
 }),
 rear:Object.freeze({
  wishboneUpperInner:Object.freeze([.16,.47,-1.50]),wishboneLowerInner:Object.freeze([.16,.29,-1.92]),
  uprightUpper:Object.freeze([.72,.41,-1.64]),uprightLower:Object.freeze([.72,.23,-1.80]),gearboxLow:Object.freeze([.24,.28,-1.48])
 })
});

const V=(x,y,z)=>new THREE.Vector3(x,y,z);
const colors=Object.fromEntries(SYSTEM_CATALOG.map(system=>[system.id,new THREE.Color(system.color)]));

export function createSystems({scene,model,mechanics,engine,driver,garage,camera,canvas,moveCamera,showCar=()=>{},onClose=showCar,mobile=false}){
 const root=new THREE.Group();root.name='Camadas internas · sistemas reais';root.visible=false;root.renderOrder=8;scene.add(root);
 const groups=new Map(),materials=[],geometries=[],textures=[],animations=[];
 let enabled=false,active='overview',currentView='hero',ghostEntries=[],ghostOn=false,previous={},disposed=false,paused=false;
 const reducedMotion=typeof window!=='undefined'&&typeof window.matchMedia==='function'?window.matchMedia('(prefers-reduced-motion: reduce)'):{matches:false};
 const onVisibilityChange=()=>{paused=document.hidden;};
 if(typeof document!=='undefined')document.addEventListener('visibilitychange',onVisibilityChange,{passive:true});
 const tagColor='#e9f2f5';
 const meta=id=>SYSTEM_CATALOG.find(system=>system.id===id)||SYSTEM_CATALOG[0];
 const makeMaterial=(name,color,options={})=>{
  const opacity=options.opacity??1,m=new THREE.MeshStandardMaterial({name,color,metalness:options.metalness??.28,roughness:options.roughness??.42,emissive:color,emissiveIntensity:options.emissiveIntensity??(opacity<1?.12:.2),transparent:opacity<1,opacity,depthWrite:opacity>=.95,depthTest:true,polygonOffset:opacity<1,polygonOffsetFactor:-1,polygonOffsetUnits:-1,wireframe:options.wireframe??false});
  materials.push(m);return m;
 };
 const makeLineMaterial=(name,color,opacity=.86)=>{const m=new THREE.LineBasicMaterial({name,color,transparent:opacity<1,opacity,depthTest:true,depthWrite:false});materials.push(m);return m;};
 const add=(parent,geometry,material,position,name,rotation=[0,0,0],scale=null)=>{geometries.push(geometry);const object=new THREE.Mesh(geometry,material);object.name=name;object.position.set(...position);object.rotation.set(...rotation);if(scale)object.scale.set(...scale);object.renderOrder=10;parent.add(object);return object;};
 const box=(parent,w,h,d,position,material,name,rotation=[0,0,0])=>add(parent,new THREE.BoxGeometry(w,h,d),material,position,name,rotation);
 const rounded=(parent,w,h,d,position,material,name,rotation=[0,0,0])=>add(parent,new RoundedBoxGeometry(w,h,d,3,Math.min(.035,w/8,h/8,d/8)),material,position,name,rotation);
 const cylinder=(parent,r,h,position,material,name,rotation=[0,0,0],segments=20)=>add(parent,new THREE.CylinderGeometry(r,r,h,segments),material,position,name,rotation);
 const sphere=(parent,r,position,material,name,scale=null)=>add(parent,new THREE.SphereGeometry(r,18,12),material,position,name,[0,0,0],scale);
 const torus=(parent,r,t,position,material,name,rotation=[0,0,0])=>add(parent,new THREE.TorusGeometry(r,t,10,28),material,position,name,rotation);
 const cone=(parent,r,h,position,material,name,rotation=[0,0,0])=>add(parent,new THREE.ConeGeometry(r,h,16),material,position,name,rotation);
 const beam=(parent,a,b,r,material,name)=>{const from=V(...a),to=V(...b),delta=to.clone().sub(from),object=cylinder(parent,r,delta.length(),from.clone().add(to).multiplyScalar(.5).toArray(),material,name);object.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());object.userData.endpoints={from:[...a],to:[...b]};return object;};
 const pipe=(parent,points,r,material,name,closed=false)=>{const curve=new THREE.CatmullRomCurve3(points.map(point=>V(...point))),object=add(parent,new THREE.TubeGeometry(curve,32,r,8,closed),material,[0,0,0],name);object.userData.path=points.map(point=>[...point]);return object;};
 const edgeBox=(parent,w,h,d,position,material,name)=>{const baseGeometry=new THREE.BoxGeometry(w,h,d),geometry=new THREE.EdgesGeometry(baseGeometry);geometries.push(baseGeometry,geometry);const line=new THREE.LineSegments(geometry,material);line.name=name;line.position.set(...position);line.renderOrder=12;parent.add(line);return line;};
 const createSystem=id=>{const group=new THREE.Group();group.name=`Sistema · ${meta(id).label}`;group.userData.systemId=id;group.visible=false;root.add(group);groups.set(id,group);return group;};
 const addTag=(parent,text,position,color)=>{
   const tagCanvas=document.createElement('canvas');tagCanvas.width=640;tagCanvas.height=144;const context=tagCanvas.getContext('2d');context.fillStyle='#15202a';context.fillRect(0,0,640,144);context.fillStyle=color;context.fillRect(0,0,10,144);context.fillStyle=tagColor;context.font=`600 ${text.length>24?22:44}px Segoe UI, sans-serif`;context.textBaseline='middle';context.fillText(text,30,74);const texture=new THREE.CanvasTexture(tagCanvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=4;textures.push(texture);const material=new THREE.SpriteMaterial({name:`Etiqueta ${text}`,map:texture,transparent:true,depthWrite:false,depthTest:false,toneMapped:false});materials.push(material);const sprite=new THREE.Sprite(material);sprite.name=`Etiqueta · ${text}`;sprite.userData.systemTag=true;sprite.position.set(...position);sprite.scale.set(.52,.117,1);sprite.renderOrder=20;parent.add(sprite);return sprite;
 };
 const addPulse=(parent,points,r,material,name,speed=.22,count=3)=>{
  const curve=new THREE.CatmullRomCurve3(points.map(point=>V(...point))),pulses=[];for(let i=0;i<count;i++)pulses.push(sphere(parent,r,[0,0,0],material,`${name} pulso ${i+1}`));let phase=0;animations.push((dt)=>{phase=(phase+dt*speed)%1;pulses.forEach((pulse,index)=>curve.getPointAt((phase+index/count)%1,pulse.position));});return curve;
 };
 const localAxes={x:new THREE.Vector3(1,0,0),y:new THREE.Vector3(0,1,0),z:new THREE.Vector3(0,0,1)};
 const addSpinner=(object,axis='y',rate=.8)=>{const localAxis=localAxes[axis];if(!localAxis)throw new Error(`Eixo de rotação local inválido: ${axis}`);animations.push((dt)=>object.quaternion.copy(advanceLocalSpin(object.quaternion,axis,dt*rate)));};
 const aero=createSystem('aero'),aeroMat=makeMaterial('Aero · ciano',colors.aero),aeroLine=makeLineMaterial('Aero · linhas',colors.aero,.7);
  for(const y of [.16,.225,.29])box(aero,1.35,.032,.30,[0,y,2.25],aeroMat,`Aero asa dianteira ${y}`,[.06,0,0]);
  box(aero,1.58,.035,3.15,[0,.19,-.36],aeroMat,'Aero underfloor / assoalho');box(aero,1.16,.04,.62,[0,.31,-1.87],aeroMat,'Aero difusor',[.16,0,0]);
  box(aero,1.20,.045,.30,[0,.64,-2.23],aeroMat,'Aero asa traseira');box(aero,1.14,.045,.22,[0,.78,-2.34],aeroMat,'Aero flap DRS histórico',[-.25,0,0]);
  for(const x of [-.56,0,.56])addPulse(aero,[[x,.72,2.75],[x,.84,1.72],[x,.79,.92]],.018,aeroMat,'Aero fluxo externo',.18,2);
  for(const x of [-.42,.42])addPulse(aero,[[x,.28,.78],[x,.24,-.35],[x,.27,-1.35]],.014,aeroLine,'Aero fluxo underfloor',.22,2);
  addPulse(aero,[[0,.34,-1.52],[0,.46,-1.86],[0,.60,-2.42]],.016,aeroMat,'Aero fluxo difusor',.2,2);
  addPulse(aero,[[0,.76,-2.48],[0,.82,-2.68],[0,.86,-2.88]],.014,aeroLine,'Aero fluxo DRS · menor arrasto',.24,2);
  addTag(aero,'AERO / FLUXOS ILUSTRATIVOS',[-.72,1.02,.9],meta('aero').color);

 const structure=createSystem('structure'),structureMat=makeMaterial('Estrutura · violeta',colors.structure,{metalness:.15,roughness:.54,opacity:.25}),structureVoid=makeMaterial('Estrutura · espaço do piloto',0x1b2730,{metalness:.05,roughness:.8,opacity:.16,emissiveIntensity:.04}),structureLine=makeLineMaterial('Estrutura · contorno',colors.structure,.92);
   rounded(structure,...SURVIVAL_CELL_LAYOUT.size,SURVIVAL_CELL_LAYOUT.center,structureMat,'Survival cell didática');edgeBox(structure,...SURVIVAL_CELL_LAYOUT.size,SURVIVAL_CELL_LAYOUT.center,structureLine,'Survival cell didática · contorno');
  rounded(structure,.43,.31,.78,[0,.50,.48],structureVoid,'Abertura cockpit / espaço do piloto');
  for(const side of [-1,1]){beam(structure,[side*.40,.29,-.42],[side*.40,.78,-.42],.023,structureLine,`Longarina lateral ${side}`);beam(structure,[side*.40,.29,.82],[side*.40,.78,.82],.023,structureLine,`Longarina frontal ${side}`);}
  box(structure,.48,.12,.10,[0,.68,.86],structureMat,'Antepara dianteira');box(structure,.50,.12,.10,[0,.68,-.48],structureMat,'Antepara traseira');
  box(structure,.48,.24,.78,[0,.75,-.56],structureMat,'Pontos de montagem do motor');box(structure,.48,.25,.54,[0,.46,-1.55],structureMat,'Pontos de montagem do câmbio');
  beam(structure,[-.38,.24,.98],[-.38,.67,.98],.025,structureLine,'Zona de impacto dianteira esquerda');beam(structure,[.38,.24,.98],[.38,.67,.98],.025,structureLine,'Zona de impacto dianteira direita');
  beam(structure,[-.40,.30,-1.98],[-.40,.78,-1.98],.026,structureLine,'Zona de impacto traseira esquerda');beam(structure,[.40,.30,-1.98],[.40,.78,-1.98],.026,structureLine,'Zona de impacto traseira direita');
  for(const side of [-1,1]){sphere(structure,.035,[side*.40,.34,.82],structureLine,`Ponto de montagem suspensão dianteira ${side}`);sphere(structure,.035,[side*.40,.34,-.42],structureLine,`Ponto de montagem suspensão traseira ${side}`);}
  addTag(structure,'SURVIVAL CELL / DIDÁTICA',[-.62,1.00,.28],meta('structure').color);

  const suspension=createSystem('suspension'),suspensionMat=makeMaterial('Suspensão · âmbar',colors.suspension,{metalness:.72,roughness:.28}),suspensionLine=makeLineMaterial('Suspensão · conexões',colors.suspension,.72),mirrorPoint=(point,side)=>[side*point[0],point[1],point[2]];
  const frontLayout=SUSPENSION_LAYOUT.front;
  for(const side of [-1,1]){
   const upperUpright=mirrorPoint(frontLayout.uprightUpper,side),lowerUpright=mirrorPoint(frontLayout.uprightLower,side),rockerPivot=mirrorPoint(frontLayout.rockerHigh,side);
   beam(suspension,mirrorPoint(frontLayout.wishboneUpperInner,side),upperUpright,.018,suspensionMat,`Dianteira wishbone superior ${side}`);
   beam(suspension,mirrorPoint(frontLayout.wishboneLowerInner,side),lowerUpright,.018,suspensionMat,`Dianteira wishbone inferior ${side}`);
   box(suspension,.08,.20,.18,[side*.72,.36,1.38],suspensionMat,`Dianteira upright ${side}`);
   cylinder(suspension,.035,.24,rockerPivot,suspensionMat,`Dianteira rocker alto ${side}`,[0,0,Math.PI/2],16);
   beam(suspension,lowerUpright,rockerPivot,.016,suspensionMat,`Pushrod · upright inferior → rocker alto ${side}`);
   const damperBottom=[side*.22,.56,.90],damperTop=[side*.22,.56,1.14];beam(suspension,damperBottom,damperTop,.028,suspensionMat,`Dianteira damper ${side}`);beam(suspension,damperTop,rockerPivot,.011,suspensionLine,`Ligação damper · rocker ${side}`);
   beam(suspension,[side*.10,.56,.90],[side*.10,.56,1.14],.014,suspensionLine,`Dianteira torsion bar ${side}`);
   pipe(suspension,[lowerUpright,[side*.84,.31,1.36],[side*.86,.27,1.46]],.009,suspensionLine,`Cabo de retenção ${side}`);
  }
  const rearLayout=SUSPENSION_LAYOUT.rear;
  for(const side of [-1,1]){
   const upperUpright=mirrorPoint(rearLayout.uprightUpper,side),lowerUpright=mirrorPoint(rearLayout.uprightLower,side),gearboxPoint=mirrorPoint(rearLayout.gearboxLow,side);
   beam(suspension,mirrorPoint(rearLayout.wishboneUpperInner,side),upperUpright,.018,suspensionMat,`Traseira wishbone superior ${side}`);
   beam(suspension,mirrorPoint(rearLayout.wishboneLowerInner,side),lowerUpright,.018,suspensionMat,`Traseira wishbone inferior ${side}`);
   box(suspension,.08,.20,.18,[side*.72,.32,-1.72],suspensionMat,`Traseira upright ${side}`);
   sphere(suspension,.025,gearboxPoint,suspensionLine,`Ponto baixo didático · carcaça do câmbio ${side}`);
   cylinder(suspension,.035,.24,gearboxPoint,suspensionMat,`Traseira rocker baixo · carcaça do câmbio ${side}`,[0,0,Math.PI/2],16);
   beam(suspension,upperUpright,gearboxPoint,.016,suspensionMat,`Pullrod · upright superior → rocker baixo / carcaça do câmbio ${side}`);
   const damperBottom=[side*.22,.56,-1.54],damperTop=[side*.22,.56,-1.30];beam(suspension,damperBottom,damperTop,.028,suspensionMat,`Traseira damper ${side}`);beam(suspension,damperTop,gearboxPoint,.011,suspensionLine,`Ligação damper · rocker ${side}`);
   beam(suspension,[side*.10,.56,-1.54],[side*.10,.56,-1.30],.014,suspensionLine,`Traseira torsion bar ${side}`);
   pipe(suspension,[lowerUpright,[side*.84,.31,-1.74],[side*.86,.27,-1.64]],.009,suspensionLine,`Cabo de retenção ${side}`);
  }
  beam(suspension,[-.38,.48,.88],[.38,.48,.88],.015,suspensionMat,'Barra antirrolagem · ligação didática');beam(suspension,[-.26,.50,-1.42],[.26,.50,-1.42],.015,suspensionMat,'Heave central · ligação didática');
  addTag(suspension,'SUSPENSÃO / CADEIA DIDÁTICA',[-.74,.96,.98],meta('suspension').color);

  const steering=createSystem('steering'),steeringMat=makeMaterial('Direção · coral',colors.steering,{metalness:.62,roughness:.31}),steeringLine=makeLineMaterial('Direção · assistência esquemática',colors.steering,.62);
  const rack=cylinder(steering,.035,.86,[0,.40,1.17],steeringMat,'Rack-and-pinion mecânico · cremalheira',[0,0,Math.PI/2]);
  const pinion=cylinder(steering,.08,.12,[0,.44,1.17],steeringMat,'Pinhão',[Math.PI/2,0,0]);addSpinner(pinion,'y',1.2);
  beam(steering,[0,.58,.54],[0,.43,1.17],.022,steeringMat,'Coluna de direção');
  for(const side of [-1,1]){box(steering,.08,.20,.16,[side*.73,.34,1.38],steeringMat,`Upright dianteiro da direção ${side}`);beam(steering,[side*.06,.40,1.17],[side*.73,.34,1.38],.014,steeringMat,`Track rod / barra de direção ${side}`);pipe(steering,[[side*.18,.51,1.08],[side*.38,.49,1.24],[side*.70,.42,1.38]],.008,steeringLine,`Linha de assistência esquemática ${side}`);}
  addTag(steering,'DIREÇÃO / RACK MECÂNICO',[-.65,.86,1.22],meta('steering').color);

  const brakes=createSystem('brakes'),brakeMat=makeMaterial('Freios · vermelho',colors.brakes,{metalness:.76,roughness:.24,emissiveIntensity:.4}),brakeLine=makeLineMaterial('Freios · dutos',colors.brakes,.78),frontBrakeLine=makeLineMaterial('Freios · circuito dianteiro',0xff948c,.82),rearBrakeLine=makeLineMaterial('Freios · circuito traseiro',0xff4d67,.82),regenLine=makeLineMaterial('Freios · regeneração MGU-K',0xffd45f,.86),brakeDiscs=[];
  for(const [front,z] of [[true,1.38],[false,-1.72]])for(const side of [-1,1]){
   const disc=cylinder(brakes,front?.18:.16,.045,[side*.70,.31,z],brakeMat,`Disco carbono ${front?'dianteiro':'traseiro'} ${side}`,[0,0,Math.PI/2],28);brakeDiscs.push(disc);addSpinner(disc,'y',.7);
   box(brakes,.10,.20,.25,[side*.76,.39,z],brakeMat,`Pinça ${front?'dianteira':'traseira'} ${side}`);torus(brakes,front?.16:.14,.008,[side*.73,.31,z],brakeLine,`Anel de ventilação ${side}`,[0,Math.PI/2,0]);
   pipe(brakes,[[side*.40,.45,z],[side*.54,.39,z],[side*.69,.34,z]],.012,front?frontBrakeLine:rearBrakeLine,`Linha hidráulica ${front?'dianteira':'traseira'} ${side}`);pipe(brakes,[[side*.40,.45,z],[side*.54,.39,z],[side*.69,.34,z]],.007,brakeLine,`Duto de freio ${side}`);
  }
  box(brakes,.08,.13,.30,[-.09,.48,.72],brakeMat,'Cilindro mestre · circuito dianteiro');box(brakes,.08,.13,.30,[.09,.48,.72],brakeMat,'Cilindro mestre · circuito traseiro');box(brakes,.12,.18,.08,[0,.33,.88],brakeMat,'Pedal de freio');beam(brakes,[-.16,.48,.72],[.16,.48,.72],.012,brakeLine,'Ajuste de bias · dianteiro ↔ traseiro');pipe(brakes,[[0,.40,.88],[0,.46,.72],[-.18,.45,.42]],.010,frontBrakeLine,'Pedal → circuito dianteiro');pipe(brakes,[[0,.40,.88],[0,.46,.72],[.18,.45,.42]],.010,rearBrakeLine,'Pedal → circuito traseiro');box(brakes,.16,.12,.22,[0,.47,-.72],regenLine,'Brake-by-wire didático / MGU-K');pipe(brakes,[[.18,.45,.42],[0,.42,-.12],[0,.47,-.72]],.009,regenLine,'Contribuição regenerativa MGU-K');addPulse(brakes,[[.18,.45,.42],[0,.42,-.12],[0,.47,-.72]],.012,regenLine,'Pulso regenerativo MGU-K',.24,2);addTag(brakes,'FREIOS / DOIS CIRCUITOS',[-.72,.91,.68],meta('brakes').color);
  animations.push((dt,time)=>brakeDiscs.forEach((disc,index)=>{const heat=.35+.25*(.5+.5*Math.sin(time*2.6+index));disc.material.emissiveIntensity=heat;}));

  const legacyNodes=[];const markLegacy=node=>{node.userData.legacy2021=true;legacyNodes.push(node);return node;};
  const power=createSystem('power'),powerMat=makeMaterial('V6 · laranja',colors.power,{metalness:.7,roughness:.32}),powerDark=makeMaterial('V6 · bloco',0x303a42,{metalness:.5,roughness:.34}),powerHot=makeMaterial('V6 · quente',0xff6e42,{metalness:.44,roughness:.3,emissiveIntensity:.65}),powerAir=makeLineMaterial('V6 · admissão',0xffd08a,.82),powerIntake=makeMaterial('V6 · admissão didática',0x26333d,{metalness:.42,roughness:.30}),carbonMat=makeMaterial('V6 · carbono plenums',0x181c20,{metalness:.2,roughness:.6}),machinedAlum=makeMaterial('V6 · trompetas alumínio',0xd8e0e8,{metalness:.85,roughness:.18}),crank=cylinder(power,.026,.78,[0,.40,-.75],powerMat,'Virabrequim',[0,0,Math.PI/2],20);
 rounded(power,...POWER_FUEL_LAYOUT.powerBlock.size,POWER_FUEL_LAYOUT.powerBlock.center,powerDark,'Bloco V6');
 for(const side of [-1,1]){box(power,.16,.22,.60,[side*.20,.67,-.75],powerMat,`Cabeçote ${side}`);for(const z of [-.98,-.75,-.52]){cylinder(power,.055,.12,[side*.20,.81,z],powerMat,`Cilindro ${side} ${z}`);pipe(power,[[side*.20,.76,z],[side*.34,.75,z-.08],[side*.38,.67,z-.18]],.012,powerHot,`Coletor ${side} ${z}`);}}
  const turboAxisStart=[0,.60,-.40],turboAxisEnd=[0,.60,-1.02];
  const turboCompressor=torus(power,.14,.035,turboAxisStart,powerHot,'Turbo único · compressor',[0,0,0]),turboTurbine=torus(power,.14,.035,turboAxisEnd,powerHot,'Turbo único · turbina',[0,0,0]);
  const turboShaft=beam(power,turboAxisStart,turboAxisEnd,.035,powerHot,'Eixo comum do turbo · coaxial em Z');addSpinner(turboCompressor,'z',1.4);addSpinner(turboTurbine,'z',1.4);addSpinner(turboShaft,'y',1.4);
  const mguh=markLegacy(cylinder(power,.10,.20,[0,.60,-.70],powerHot,'MGU-H · legado 2021 · coaxial ao eixo do turbo',[Math.PI/2,0,0]));const mguHDrive=markLegacy(beam(power,[0,.60,-.60],[0,.60,-.80],.018,powerHot,'Acoplamento coaxial MGU-H · eixo do turbo'));addSpinner(mguh,'y',-1.4);addSpinner(mguHDrive,'y',-1.4);
  rounded(power,.36,.12,.26,[0,.86,-.20],powerDark,'Intercooler didático');pipe(power,[[0,.60,-.28],[0,.74,-.25],[0,.86,-.20]],.014,powerAir,'Compressor → intercooler · ar pressurizado');pipe(power,[[0,.86,-.07],[0,.87,-.34],[0,.88,-.45]],.014,powerAir,'Intercooler → manifold dos plenums');
  for(const side of [-1,1]){const plenumCenter=[side*.20,.88,-.75];rounded(power,.20,.07,.62,plenumCenter,powerIntake,`Plenum de admissão · ${side<0?'esquerdo':'direito'} · HIP`);edgeBox(power,.20,.07,.62,plenumCenter,powerAir,`Plenum de admissão · contorno HIP ${side}`);pipe(power,[[0,.88,-.45],[side*.20,.88,-.45]],.016,powerAir,`Manifold → plenum ${side<0?'esquerdo':'direito'} · HIP`);for(const z of [-.95,-.75,-.55]){add(power,new THREE.CylinderGeometry(.068,.032,.12,16,1,true),machinedAlum,[side*.20,.96,z],`Velocity stack / trompeta representativa ${side} ${z}`);torus(power,.068,.009,[side*.20,1.025,z],machinedAlum,`Boca aberta da velocity stack ${side} ${z}`,[Math.PI/2,0,0]);pipe(power,[[side*.20,.915,z],[side*.20,.90,z]],.008,powerAir,`Plenum → velocity stack ${side} ${z}`);}}
  const wastegate=torus(power,.055,.014,[.17,.57,-.79],powerHot,'Wastegate',[Math.PI/2,0,0]);pipe(power,[[.14,.70,-.54],[.17,.62,-.72],[.17,.57,-.79]],.010,powerHot,'Linha da wastegate');
  pipe(power,[[0,.54,-1.02],[0,.54,-1.45],[0,.48,-1.82]],.022,powerHot,'Escapamento central');pipe(power,[[-.14,.69,-.54],[-.08,.61,-.66],[0,.56,-.76]],.014,powerHot,'Coletor quente para turbina');pipe(power,[[.14,.69,-.54],[.08,.61,-.66],[0,.56,-.76]],.014,powerHot,'Coletor quente para turbina');addSpinner(crank,'y',1.7);addTag(power,'V6 / TURBO DIVIDIDO',[-.70,1.00,-.62],meta('power').color);const mguhTag=markLegacy(addTag(power,'MGU-H · LEGADO 2021',[.30,1.00,-.62],meta('power').color));addTag(power,'2026 · MGU-H REMOVIDO',[.30,.90,-.62],meta('ers').color);

  const ers=createSystem('ers'),powerCardName='Motor V6 turbo',ersMat=makeMaterial('ERS · amarelo',colors.ers,{metalness:.38,roughness:.30,emissiveIntensity:.42}),ersLine=makeLineMaterial('ERS · alta tensão',colors.ers,.95),ersControlMat=makeMaterial('ERS · controle',0xffb84d,{metalness:.55,roughness:.28,emissiveIntensity:.5}),energy=[];
  rounded(ers,...POWER_FUEL_LAYOUT.energyStore.size,POWER_FUEL_LAYOUT.energyStore.center,ersMat,'Energy store · bateria HV · sob a célula didática');for(const x of [-.18,-.06,.06,.18])box(ers,.06,.08,.12,[x,.28,-.28],ersMat,`Módulo energy store ${x}`);
  rounded(ers,.27,.16,.30,[0,.53,-.62],ersControlMat,'Control electronics / inverter');
  const mguk=cylinder(ers,.10,.24,[-.18,.36,-.75],ersMat,'MGU-K · recuperação cinética · acoplado ao virabrequim', [0,0,Math.PI/2]),mgukGear=cylinder(ers,.06,.08,[-.10,.40,-.75],ersMat,'Pinhão didático MGU-K · virabrequim',[0,0,Math.PI/2]);addSpinner(mguk,'y',1.1);addSpinner(mgukGear,'y',1.1);beam(ers,[-.10,.40,-.75],[-.18,.36,-.75],.018,ersLine,'Acoplamento mecânico MGU-K · virabrequim');
  const ersPath=[[0,.33,.02],[0,.44,-.28],[0,.50,-.62],[0,.52,-1.28]],ersRecovery=[[0,.48,-1.28],[0,.40,-.88],[0,.32,-.48],[0,.28,.02]],ersDelivery=[[0,.28,.02],[0,.40,-.24],[0,.50,-.62],[0,.48,-1.28]];
  addPulse(ers,ersRecovery,.015,ersLine,'Recuperação para energy store',.30,2);addPulse(ers,ersDelivery,.015,ersLine,'Entrega ao MGU-K',.34,2);pipe(ers,[[0,.31,.02],[-.34,.38,.12],[-.42,.62,-.24]],.012,ersLine,'Cabo laranja esquerdo');pipe(ers,[[0,.31,.02],[.34,.38,.12],[.42,.62,-.24]],.012,ersLine,'Cabo laranja direito');
  addTag(ers,`MGU-H legado → ${powerCardName}`,[.28,.72,-.02],meta('power').color);addTag(ers,'ERS / 2021 → 2026',[.28,.90,-.02],meta('ers').color);
  energy.push({object:mguk,base:mguk.material});

  const cooling=createSystem('cooling'),coolMat=makeMaterial('Cooling · verde',colors.cooling,{metalness:.25,roughness:.38}),coolAirLine=makeLineMaterial('Cooling · ar de admissão',0xffd08a,.82),coolEngineLine=makeLineMaterial('Cooling · motor/óleo',0x6de0a2,.82),coolERSLine=makeLineMaterial('Cooling · ERS/bateria',0x7fd8ff,.82),coolHydLine=makeLineMaterial('Cooling · hidráulica/câmbio',0xffd27e,.82),coolPulse=makeMaterial('Cooling · pulso',0xd9fff1,{metalness:.1,roughness:.3,emissiveIntensity:.85});
  rounded(cooling,.13,.38,.88,[-.70,.49,-.08],coolMat,'Intercooler ar-ar · sidepod esquerdo · HIP',[0,0,-.70]);for(let i=0;i<10;i++)box(cooling,.012,.30,.018,[-.70-.09+i*.02,.49,-.48+i*.09],coolEngineLine,`Aleta intercooler ar-ar · esquerda · HIP ${i}`,[0,0,-.70]);
  const rightExchangers=[['motor / óleo',.34,coolEngineLine],['ERS / bateria',.50,coolERSLine],['hidráulica / câmbio',.66,coolHydLine]];for(const [label,y,line] of rightExchangers){box(cooling,.13,.10,.88,[.70,y,-.08],coolMat,`Trocador ${label} · sidepod direito · HIP`);for(let i=0;i<7;i++)box(cooling,.012,.07,.018,[.78,y-.035+i*.01,-.38+i*.10],line,`Aleta trocador ${label} · direita · HIP ${i}`);}
  const coolingAir=[ [0,.60,-.28],[-.34,.63,-.20],[-.58,.55,.14],[-.70,.49,.35] ],coolingEngine=[[0,.56,-.72],[.28,.58,-.58],[.54,.48,.02],[.70,.34,.40]],coolingERS=[[0,.53,-.62],[.28,.56,-.42],[.56,.50,.06],[.70,.50,.40]],coolingHyd=[[0,.52,-1.35],[.28,.52,-1.24],[.56,.56,-.20],[.70,.66,.40]];
  pipe(cooling,coolingAir,.014,coolAirLine,'Ar de admissão → intercooler esquerdo · HIP');pipe(cooling,coolingEngine,.014,coolEngineLine,'Circuito motor / óleo → trocador correspondente');pipe(cooling,coolingERS,.014,coolERSLine,'Circuito ERS / bateria → trocador correspondente');pipe(cooling,coolingHyd,.014,coolHydLine,'Circuito hidráulica / câmbio → trocador correspondente');addPulse(cooling,coolingAir,.018,coolPulse,'Fluxo ar de admissão',.23,2);addPulse(cooling,coolingEngine,.018,coolPulse,'Fluxo motor / óleo',.25,2);addPulse(cooling,coolingERS,.018,coolPulse,'Fluxo ERS / bateria',.22,2);addPulse(cooling,coolingHyd,.018,coolPulse,'Fluxo hidráulica / câmbio',.28,2);addTag(cooling,'COOLING / FLUXOS',[.30,1.03,-.04],meta('cooling').color);

  const fuel=createSystem('fuel'),fuelMat=makeMaterial('Fuel cell · dourado',colors.fuel,{metalness:.1,roughness:.48,opacity:.58}),fuelContainMat=makeMaterial('Fuel cell · contenção',0xf2d28d,{metalness:.2,roughness:.55,opacity:.16}),fuelLine=makeLineMaterial('Fuel cell · linhas seguras',colors.fuel,.8);
  edgeBox(fuel,...POWER_FUEL_LAYOUT.fuelContainment.size,POWER_FUEL_LAYOUT.fuelContainment.center,fuelLine,'Contenção estrutural da célula · compacta · entre survival cell e motor');const bladder=rounded(fuel,...POWER_FUEL_LAYOUT.fuelCell.size,POWER_FUEL_LAYOUT.fuelCell.center,fuelMat,'Célula única flexível / bladder · compacta · atrás do piloto');rounded(fuel,.34,.24,.10,POWER_FUEL_LAYOUT.fuelCell.center,fuelContainMat,'Casca de contenção esquemática · compacta · entre survival cell e motor');for(const z of [-.31,-.28,-.25])beam(fuel,[-.14,.31,z],[.14,.31,z],.010,fuelLine,`Baffle combustível ${z}`);for(const z of [-.33,-.23]){beam(fuel,[-.18,.30,z],[-.18,.62,z],.012,fuelLine,`Cinta célula esquerda ${z}`);beam(fuel,[.18,.30,z],[.18,.62,z],.012,fuelLine,`Cinta célula direita ${z}`);}
  sphere(fuel,.03,POWER_FUEL_LAYOUT.fuelPump,fuelLine,'Bomba de combustível');sphere(fuel,.025,POWER_FUEL_LAYOUT.fuelPressureSensor,fuelLine,'Sensor de pressão do combustível');sphere(fuel,.035,POWER_FUEL_LAYOUT.fuelBreakaway,fuelLine,'Válvula breakaway auto-selante');pipe(fuel,POWER_FUEL_LAYOUT.fuelRoute,.012,fuelLine,'Linha segura de alimentação · bomba → motor · fora do cockpit');animations.push((dt,time)=>{bladder.scale.y=1+.018*Math.sin(time*.7);});addTag(fuel,'FUEL CELL / SEGURA',[-.42,.92,-.28],meta('fuel').color);

  const transmission=createSystem('transmission'),transMat=makeMaterial('Transmissão · aço',colors.transmission,{metalness:.82,roughness:.25}),transShellMat=makeMaterial('Transmissão · carcaça translúcida',colors.transmission,{metalness:.55,roughness:.36,opacity:.20}),transLine=makeLineMaterial('Transmissão · inspeção',0xe8f1f5,.78),gearMat=makeMaterial('Transmissão · engrenagens',0x68747e,{metalness:.9,roughness:.22}),reverseMat=makeMaterial('Transmissão · ré',0x93a7b8,{metalness:.9,roughness:.22}),tripodMat=makeMaterial('Transmissão · juntas didáticas',0xd8e2ea,{metalness:.86,roughness:.24}),gears=[];
  rounded(transmission,.54,.36,.82,[0,.46,-1.48],transShellMat,'Carcaça do câmbio didática translúcida · não é corte real');edgeBox(transmission,.54,.36,.82,[0,.46,-1.48],transLine,'Contorno da carcaça translúcida');edgeBox(transmission,.40,.25,.02,[0,.60,-1.06],transLine,'Janela didática de inspeção das relações · não é corte real');const primary=cylinder(transmission,.035,.74,[-.10,.51,-1.48],transMat,'Eixo primário',[Math.PI/2,0,0],16),secondary=cylinder(transmission,.035,.74,[.10,.51,-1.48],transMat,'Eixo secundário',[Math.PI/2,0,0],16);addSpinner(primary,'y',.42);addSpinner(secondary,'y',-.42);
  for(const relation of [1,2,3,4,5,6,7,8]){const z=-1.82+(relation-1)*.095;const primaryGear=cylinder(transmission,.075,.075,[-.10,.55,z],gearMat,`Engrenagem ${relation} F · primária`,[Math.PI/2,0,0],20);const secondaryGear=cylinder(transmission,.11,.075,[.10,.47,z],gearMat,`Engrenagem ${relation} F · secundária`,[Math.PI/2,0,0],20);gears.push(primaryGear,secondaryGear);addSpinner(primaryGear,'y',.48);addSpinner(secondaryGear,'y',-.48);}
  const reverse=cylinder(transmission,.10,.075,[0,.64,-1.10],reverseMat,'Engrenagem R · ré',[Math.PI/2,0,0],20);gears.push(reverse);addSpinner(reverse,'y',-.34);const differential=cylinder(transmission,.17,.28,[0,.38,-1.94],transMat,'Diferencial',[0,0,Math.PI/2]);addSpinner(differential,'y',.65);for(const side of [-1,1]){const output=[side*.24,.38,-1.94],joint=[side*.36,.34,-1.88],shaftEnd=[side*.74,.32,-1.78];beam(transmission,[0,.37,-1.94],output,.022,transMat,`Saída do diferencial ${side}`);sphere(transmission,.055,joint,tripodMat,`Junta tripóide esquemática · centro ${side}`);for(let roller=0;roller<3;roller++){const angle=roller*Math.PI*2/3,rollerPoint=[joint[0]+side*.065*Math.cos(angle),joint[1]+.065*Math.sin(angle),joint[2]+.025*Math.sin(angle)];beam(transmission,joint,rollerPoint,.009,tripodMat,`Braço da junta tripóide esquemática ${roller+1} ${side}`);sphere(transmission,.016,rollerPoint,tripodMat,`Roletinho da junta tripóide esquemática ${roller+1} ${side}`);}beam(transmission,output,joint,.022,transMat,`Saída → junta tripóide esquemática ${side}`);beam(transmission,joint,shaftEnd,.022,transMat,`Driveshaft → junta tripóide esquemática ${side}`);}addTag(transmission,'8 F + 1 R / DIF.',[-.70,.94,-1.47],meta('transmission').color);

 const safety=createSystem('safety'),safetyMat=makeMaterial('Safety · magenta',colors.safety,{metalness:.35,roughness:.34,emissiveIntensity:.38}),safetyLine=makeLineMaterial('Safety · retenção',colors.safety,.9),safetyImpactMat=makeMaterial('Safety · estruturas de impacto',0xff754f,{metalness:.42,roughness:.32,emissiveIntensity:.46});
 pipe(safety,[[-.28,.66,.72],[-.24,.88,.72],[0,1.02,.78],[.24,.88,.72],[.28,.66,.72]],.028,safetyMat,'Halo arco');beam(safety,[0,.66,.72],[0,.98,.76],.024,safetyMat,'Halo perna central');box(safety,.28,.27,.32,[0,.33,2.17],safetyImpactMat,'Crash structure frontal');box(safety,.34,.30,.38,[0,.39,-2.12],safetyImpactMat,'Crash structure traseira');for(const side of [-1,1]){beam(safety,[side*.42,.42,.35],[side*.78,.42,.35],.022,safetyMat,`Estrutura lateral protegida ${side}`);beam(safety,[side*.44,.34,.58],[side*.44,.63,.58],.017,safetyImpactMat,`Estrutura anti-intrusão lateral ${side}`);for(const [z,anchorY,offset] of [[1.34,.30,.12],[-1.72,.34,-.12]])for(const tether of [0,1,2]){const anchorX=side*(.22+tether*.16),wheelX=side*(.88-tether*.04);pipe(safety,[[wheelX,.28+tether*.045,z+offset],[side*(.56+tether*.04),anchorY+tether*.035,z+offset*.5],[anchorX,.40+tether*.03,z]],.0075,safetyLine,`Cabo de retenção da roda ${tether+1} ${side} ${z}`);}}
 pipe(safety,[[-.16,.62,-.34],[-.16,.91,-.34],[0,1.12,-.34],[.16,.91,-.34],[.16,.62,-.34]],.024,safetyLine,'Estrutura primária de capotamento');
 addTag(safety,'SAFETY',[-.58,1.16,.80],meta('safety').color);

 const cockpit=createSystem('cockpit'),cockpitMat=makeMaterial('Cockpit · lilás',colors.cockpit,{metalness:.12,roughness:.62}),cockpitLine=makeLineMaterial('Cockpit · arnês',colors.cockpit,.84),fhrMat=makeMaterial('Cockpit · FHR/HANS',0xf1ddff,{metalness:.18,roughness:.5,emissiveIntensity:.32});
 rounded(cockpit,.40,.13,.76,[0,.37,.42],cockpitMat,'Banco moldado',[.08,0,0]);box(cockpit,.36,.20,.08,[0,.54,.04],cockpitMat,'Headrest / apoio de cabeça');sphere(cockpit,.13,[0,.77,.38],cockpitMat,'Interface didática do capacete');
 for(const side of [-1,1]){beam(cockpit,[side*.20,.72,.38],[0,.46,.20],.018,cockpitLine,`Arnês ombro ${side}`);beam(cockpit,[side*.20,.47,.48],[0,.43,.22],.018,cockpitLine,`Arnês quadril ${side}`);beam(cockpit,[side*.16,.34,.48],[0,.43,.22],.018,cockpitLine,`Arnês subabdominal ${side}`);}
 sphere(cockpit,.045,[0,.44,.20],cockpitLine,'Fecho central');pipe(cockpit,[[-.22,.67,.32],[-.30,.80,.42],[0,.84,.52],[.30,.80,.42],[.22,.67,.32]],.018,fhrMat,'FHR / HANS yoke');for(const side of [-1,1])beam(cockpit,[side*.22,.80,.42],[side*.11,.80,.48],.009,fhrMat,`FHR / HANS interface capacete ${side}`);box(cockpit,.11,.06,.22,[-.10,.22,.91],cockpitMat,'Pedal acelerador');box(cockpit,.11,.10,.22,[.10,.23,.91],cockpitLine,'Pedal freio');pipe(cockpit,[[.22,.72,.55],[.34,.69,.40],[.36,.54,.24]],.012,cockpitLine,'Tubo de hidratação');addTag(cockpit,'COCKPIT / FHR',[-.61,1.05,.44],meta('cockpit').color);

 const wheel=createSystem('wheel'),wheelMat=makeMaterial('Volante · azul',colors.wheel,{metalness:.48,roughness:.28}),wheelDark=makeMaterial('Volante · carcaça',0x1d252d,{metalness:.52,roughness:.27}),ledMat=makeMaterial('Volante · LEDs',0xffd45d,{metalness:.2,roughness:.22,emissiveIntensity:1}),leds=[];
 torus(wheel,.16,.032,[0,.60,.52],wheelDark,'Aro do volante',[0,0,0]);box(wheel,.30,.16,.035,[0,.60,.53],wheelMat,'Placa do volante');box(wheel,.11,.065,.042,[0,.63,.555],wheelDark,'Display central');cylinder(wheel,.055,.18,[0,.60,.39],wheelDark,'Coluna de direção',[Math.PI/2,0,0]);torus(wheel,.07,.018,[0,.60,.48],wheelMat,'Cubo do volante',[Math.PI/2,0,0]);torus(wheel,.085,.014,[0,.60,.47],wheelMat,'Quick-release',[Math.PI/2,0,0]);for(const x of [-.11,-.055,0,.055,.11]){const led=box(wheel,.025,.018,.016,[x,.695,.55],ledMat,`LED shift ${x}`);leds.push(led);}for(const side of [-1,1]){box(wheel,.035,.11,.03,[side*.16,.60,.52],wheelMat,`Empunhadura ${side}`);box(wheel,.05,.14,.02,[side*.12,.48,.51],wheelDark,`Paddle ${side}`);for(const y of [.56,.61,.66])sphere(wheel,.014,[side*.08,y,.56],ledMat,`Botão ${side} ${y}`);}
 animations.push((dt,time)=>leds.forEach((led,index)=>{led.material.emissiveIntensity=.45+.55*(.5+.5*Math.sin(time*4+index*.8));}));addTag(wheel,'VOLANTE / COMANDOS',[.34,.90,.52],meta('wheel').color);

 const sensors=createSystem('sensors'),sensorMat=makeMaterial('Sensores · ciano',colors.sensors,{metalness:.42,roughness:.24,emissiveIntensity:.42}),sensorLine=makeLineMaterial('Sensores · sinal',colors.sensors,.78),sensorPulse=makeMaterial('Sensores · pulso',0xe8ffff,{metalness:.1,roughness:.2,emissiveIntensity:1}),sensorPressure=makeLineMaterial('Sensores · pressão Pitot',0xbaf5ff,.84),sensorTelemetry=makeLineMaterial('Sensores · telemetria',0x70d8ff,.84);
 beam(sensors,[0,.31,2.30],[0,.31,2.78],.012,sensorMat,'Tubo de Pitot');sphere(sensors,.035,[0,.31,2.80],sensorPulse,'Cabeça Pitot');pipe(sensors,[[0,.33,2.74],[0,.38,2.30],[0,.40,1.86]],.006,sensorPressure,'Linha de pressão Pitot');for(const side of [-1,1]){beam(sensors,[side*.75,.32,1.40],[side*.82,.40,1.52],.012,sensorMat,`Sensor wheel speed dianteiro ${side}`);beam(sensors,[side*.73,.31,-1.72],[side*.82,.40,-1.60],.012,sensorMat,`Sensor wheel speed traseiro ${side}`);sphere(sensors,.025,[side*.74,.42,1.36],sensorPulse,`Sensor temperatura freio ${side}`);}
 rounded(sensors,.28,.16,.30,[0,.56,-.08],sensorMat,'ECU / unidade de aquisição');sphere(sensors,.025,[-.22,.65,-.02],sensorPulse,'Acelerômetro didático');sphere(sensors,.025,[.22,.65,-.02],sensorPulse,'Sensor pressão didático');sphere(sensors,.025,[0,.71,-.24],sensorPulse,'Sensor temperatura motor');
 pipe(sensors,[[0,.48,-.08],[-.34,.50,.12],[-.54,.44,.62]],.007,sensorLine,'Barramento de dados');sphere(sensors,.045,[0,.46,-2.18],sensorMat,'Microfone/acústica do motor');for(const x of [-.18,.18])beam(sensors,[x,.86,-.36],[x,.99,-.32],.009,sensorLine,`Antena ${x}`);const telemetryPath=[[0,.56,-.08],[.28,.64,-.32],[.46,.82,-.62],[.58,1.00,-.92]];pipe(sensors,telemetryPath,.005,sensorTelemetry,'Telemetria carro → box');addPulse(sensors,telemetryPath,.015,sensorPulse,'Telemetria carro → box',.30,3);addPulse(sensors,[[0,.33,2.72],[0,.38,2.30],[0,.40,1.86]],.011,sensorPulse,'Pressão Pitot',.22,2);addTag(sensors,'SENSORES / AQUISIÇÃO',[.32,1.03,1.76],meta('sensors').color);

 const ui={list:document.getElementById('system-list'),detail:document.getElementById('system-detail'),title:document.getElementById('system-title'),kicker:document.getElementById('system-kicker'),description:document.getElementById('system-description'),chapter:document.getElementById('system-chapter'),count:document.getElementById('system-part-count'),overview:document.getElementById('system-overview'),back:document.getElementById('system-close'),hint:document.querySelector('.hint'),context:document.getElementById('system-context'),chapters:[...document.querySelectorAll('.system-chapters a')],views:[...document.querySelectorAll('[data-view]')]};
 let ersContext='legacy2021',contextToggle=null;
 if(ui.detail&&!document.getElementById('ers-context-toggle')){contextToggle=document.createElement('button');contextToggle.id='ers-context-toggle';contextToggle.type='button';contextToggle.className='wide';contextToggle.setAttribute('aria-pressed','false');ui.detail.append(contextToggle);}
 const originalHint=ui.hint?.textContent||'';
 const systemsHint='SISTEMAS: USE TAB E SETAS PARA ESCOLHER · ENTER/ESPAÇO PARA ABRIR';
 if(ui.detail&&ui.list&&ui.detail.parentElement===ui.list.parentElement)ui.detail.parentElement.insertBefore(ui.detail,ui.list);
 const cardFor=id=>ui.list?.querySelector(`[data-system="${id}"]`);
 const syncView=name=>ui.views.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===name)));
 function setERSContext(mode){ersContext=mode==='current2026'?'current2026':'legacy2021';legacyNodes.forEach(node=>{node.visible=ersContext==='legacy2021';});if(active==='ers'){updateUI('ers');frame('ers',directions[currentView],false);}}
 function updateUI(id=active){
  if(disposed)return;
  const overview=id==='overview',system=overview?null:meta(id),rovingId=overview?SYSTEM_CATALOG[0]?.id:id;syncView(currentView);if(ui.title)ui.title.textContent=overview?'Visão geral dos sistemas':system.label;if(ui.kicker)ui.kicker.textContent=overview?'CAMADAS INTERNAS / VISÃO DIDÁTICA':`${system.number} / ${system.short}`;if(ui.description)ui.description.textContent=overview?'Visão esquemática original: selecione uma camada para seguir conexões entre conjuntos. Não é CAD nem validação física.':`${system.description} Simplificação didática; conexões indicam função, não escala homologada.${id==='ers'?` Contexto ativo: ${ersContext==='legacy2021'?'arquitetura do vídeo / 2021 (MGU-H legado visível)':'arquitetura atual / 2026 (MGU-H removido)'}.`:''}`;if(ui.chapter)ui.chapter.textContent=overview?'14 sistemas · vídeo de referência':`Capítulo ${system.chapter} · vídeo de referência`;if(ui.count)ui.count.textContent=overview?'14 CAMADAS':`${system.number} / 14`;if(contextToggle){contextToggle.hidden=id!=='ers';contextToggle.textContent=ersContext==='legacy2021'?'Ver contexto atual 2026':'Voltar ao vídeo / 2021';contextToggle.setAttribute('aria-pressed',String(ersContext==='current2026'));}if(ui.overview){ui.overview.setAttribute('aria-pressed',String(overview));ui.overview.textContent=overview?'Todos os sistemas visíveis':'Mostrar todos os sistemas';ui.overview.style.color=overview?'#fff':'';ui.overview.style.backgroundColor=overview?'var(--red)':'';}if(ui.hint)ui.hint.style.textShadow=enabled?'0 1px 3px var(--paper),0 0 8px var(--paper)':'';SYSTEM_CATALOG.forEach((item,index)=>{const card=cardFor(item.id);if(card){const selected=!overview&&item.id===id;card.setAttribute('aria-pressed',String(selected));card.tabIndex=item.id===rovingId?0:-1;const chapterLink=ui.chapters[index];if(chapterLink){if(selected)chapterLink.setAttribute('aria-current','true');else chapterLink.removeAttribute('aria-current');}}});if(overview)ui.chapters.forEach(link=>link.removeAttribute('aria-current'));if(ui.detail)ui.detail.style.setProperty('--system-color',overview?'#d92135':system.color);}
 function objectFor(id){return id==='overview'?root:groups.get(id);}
 function geometryBounds(object){const bounds=new THREE.Box3().makeEmpty();object.traverse(node=>{if(!node.visible||node.userData.systemTag||(!node.isMesh&&!node.isLine&&!node.isPoints))return;bounds.expandByObject(node);});return bounds;}
 function viewportAspect(){const width=canvas?.clientWidth||canvas?.width,height=canvas?.clientHeight||canvas?.height;return width>0&&height>0?width/height:Math.max(camera?.aspect??1,.5);}
 const directions={hero:[1,.35,1.18],side:[1,.12,0],front:[0,.16,1],rear:[0,.18,-1],top:[.001,1,0],bottom:[.001,-1,0]};
 function frame(id,direction=directions[currentView],animate=true){if(disposed||typeof moveCamera!=='function')return;const object=objectFor(id);if(!object)return;object.updateMatrixWorld(true);const bounds=geometryBounds(object);if(bounds.isEmpty())return;const target=bounds.getCenter(new THREE.Vector3());if(id==='overview')target.y=.45;const dir=new THREE.Vector3(...direction).normalize(),worldUp=new THREE.Vector3(0,1,0),right=new THREE.Vector3().crossVectors(worldUp,dir);if(right.lengthSq()<1e-6)right.set(1,0,0);else right.normalize();const up=new THREE.Vector3().crossVectors(dir,right).normalize(),halfVertical=Math.tan(THREE.MathUtils.degToRad(camera?.fov??45)/2),halfHorizontal=halfVertical*Math.max(viewportAspect(),.1);let required=0;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const offset=new THREE.Vector3(x,y,z).sub(target),depth=offset.dot(dir);required=Math.max(required,depth+Math.abs(offset.dot(right))/halfHorizontal,depth+Math.abs(offset.dot(up))/halfVertical);}const size=bounds.getSize(new THREE.Vector3()),minimum=id==='overview'?(mobile?6.8:6.4):(mobile?2.9:2.35),distance=THREE.MathUtils.clamp(Math.max(required*1.18,size.length()*1.08,minimum),minimum,30);moveCamera(target.clone().addScaledVector(dir,distance),target,animate);}
 function show(id='overview',animate=true){if(disposed)return;if(!groups.has(id)&&id!=='overview')id='overview';setEnabled(true);active=id;groups.forEach((group,key)=>{group.visible=id==='overview'||key===id;group.traverse(node=>{if(node.userData.systemTag)node.visible=id!=='overview';});});updateUI(id);frame(id,directions[currentView],animate);}
 function view(name){if(disposed||!enabled)return;currentView=directions[name]?name:'hero';syncView(currentView);frame(active,directions[currentView],false);}
 function captureGhost(){if(disposed||ghostEntries.length||!model?.traverse)return;model.traverse(object=>{if(!object.isMesh)return;const original=object.material;const cloneMaterial=material=>{if(!material?.clone)return material;const clone=material.clone();if('color' in clone)clone.color.set('#8b9aa4');if('map' in clone)clone.map=null;if('emissive' in clone){clone.emissive.set('#22303a');clone.emissiveIntensity=.16;}clone.transparent=true;clone.opacity=.105;clone.depthWrite=false;clone.depthTest=true;return clone;};ghostEntries.push({object,original,ghost:Array.isArray(original)?original.map(cloneMaterial):cloneMaterial(original)});});}
 function setGhost(on){if(disposed)return;captureGhost();if(on&&!ghostOn){ghostEntries.forEach(entry=>{entry.object.material=entry.ghost;});ghostOn=true;}else if(!on&&ghostOn){ghostEntries.forEach(entry=>{entry.object.material=entry.original;});ghostOn=false;}}
 function setEnabled(on){if(disposed||on===enabled)return;enabled=on;root.visible=on;document.body.classList.toggle('systems-active',on);if(ui.hint)ui.hint.textContent=on?systemsHint:originalHint;if(on){previous={model:model?.visible,driver:driver?.root.visible,engine:engine?.root.visible};if(garage?.enabled)garage.setEnabled(false);if(model)model.visible=true;if(driver?.root)driver.root.visible=false;if(engine?.root)engine.root.visible=false;setGhost(true);}else{setGhost(false);if(model)model.visible=previous.model??true;if(driver?.root)driver.root.visible=previous.driver??true;if(engine?.root)engine.root.visible=previous.engine??false;root.visible=false;}}
 const onSystemClick=event=>show(event.currentTarget.dataset.system);
 const onSystemKey=event=>{const cards=[...ui.list?.querySelectorAll('[data-system]')||[]],index=cards.indexOf(event.currentTarget);if(!cards.length)return;let next=index;if(event.key==='ArrowDown'||event.key==='ArrowRight')next=(index+1)%cards.length;else if(event.key==='ArrowUp'||event.key==='ArrowLeft')next=(index-1+cards.length)%cards.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=cards.length-1;else if(event.key==='Enter'||event.key===' '){event.preventDefault();show(event.currentTarget.dataset.system);return;}else return;event.preventDefault();cards[next].focus();show(cards[next].dataset.system);};
 const onOverviewClick=()=>show('overview');
 const onBackClick=()=>{setEnabled(false);active='overview';updateUI();onClose();};
 const onContextToggle=()=>setERSContext(ersContext==='legacy2021'?'current2026':'legacy2021');
 if(ui.list)SYSTEM_CATALOG.forEach((system,index)=>{const card=cardFor(system.id);if(!card)return;card.tabIndex=index===0?0:-1;card.addEventListener('click',onSystemClick);card.addEventListener('keydown',onSystemKey);});
 ui.overview?.addEventListener('click',onOverviewClick);
 ui.back?.addEventListener('click',onBackClick);
 contextToggle?.addEventListener('click',onContextToggle);
 setERSContext('legacy2021');
 updateUI('overview');
 return {root,groups,show,view,activate:show,deactivate:()=>setEnabled(false),setPaused(value){paused=Boolean(value);},setERSContext,reset:()=>show('overview',false),get active(){return enabled?active:null;},get enabled(){return enabled;},get context(){return ersContext;},get paused(){return paused||reducedMotion.matches;},update(dt,time=performance.now()/1000){if(disposed||!enabled||paused||reducedMotion.matches||document.hidden)return;animations.forEach(animation=>animation(Math.min(Math.max(dt,0),.05),time));},dispose(){if(disposed)return;setEnabled(false);document.removeEventListener('visibilitychange',onVisibilityChange);ui.overview?.removeEventListener('click',onOverviewClick);ui.back?.removeEventListener('click',onBackClick);contextToggle?.removeEventListener('click',onContextToggle);SYSTEM_CATALOG.forEach(system=>{const card=cardFor(system.id);card?.removeEventListener('click',onSystemClick);card?.removeEventListener('keydown',onSystemKey);});ghostEntries.forEach(entry=>{for(const material of [].concat(entry.ghost)){if(material&&material!==entry.original&&material.dispose)material.dispose();}});materials.forEach(material=>material.dispose());geometries.forEach(geometry=>geometry.dispose());textures.forEach(texture=>texture.dispose());root.removeFromParent();disposed=true;}};
}
